import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'

import { getOrderErrorMessage, runPlatformAction, type OrderConfiguration, type ReagentOrder } from '#/api/order-management'
import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '#/components/ui/dialog'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import { CancellationDecisionPanel } from './CancellationDecisionPanel'

export function ReagentOperationsPanel({ order, configuration, onSaved }: { order: ReagentOrder; configuration: OrderConfiguration; onSaved: () => Promise<void> }) {
  const [dialog, setDialog] = useState<'adjustment' | 'shipment' | null>(null)
  const firstSubstitutableLine = order.lines.find((line) => line.shippedQuantity === 0 && line.cancelledQuantity === 0)
  const [originalLineId, setOriginalLineId] = useState(firstSubstitutableLine?.id ?? '')
  const [proposedOfferingId, setProposedOfferingId] = useState('')
  const [adjustedQuantity, setAdjustedQuantity] = useState(String(firstSubstitutableLine?.remainingQuantity ?? ''))
  const [adjustmentReason, setAdjustmentReason] = useState('')
  const [shipmentLineId, setShipmentLineId] = useState(order.lines.find((line) => line.remainingQuantity > 0)?.id ?? '')
  const [shipmentQuantity, setShipmentQuantity] = useState('')
  const [carrier, setCarrier] = useState('')
  const [service, setService] = useState('')
  const [trackingNumber, setTrackingNumber] = useState('')
  const [shippedAt, setShippedAt] = useState(new Date().toISOString().slice(0, 16))
  const [lotBatchNumber, setLotBatchNumber] = useState('')
  const [expiresAt, setExpiresAt] = useState('')
  const partnerOfferings = configuration.reagentOfferings.filter((offering) => offering.partnerOrganizationId === order.organizationId && offering.isActive)
  const selectedLine = order.lines.find((line) => line.id === shipmentLineId)
  const mutation = useMutation({
    mutationFn: async () => {
      if (dialog === 'adjustment') return runPlatformAction<ReagentOrder>(`reagent-orders/${order.id}/adjustments`, { version: order.version, originalLineId, proposedOfferingId, quantity: Number(adjustedQuantity), reason: adjustmentReason })
      if (dialog === 'shipment') return runPlatformAction<ReagentOrder>(`reagent-orders/${order.id}/shipments`, { version: order.version, carrier, service: service || null, trackingNumber, shippedAt: new Date(shippedAt).toISOString(), lines: [{ orderLineId: shipmentLineId, quantity: Number(shipmentQuantity), lotBatchNumber, expiresAt: expiresAt || null }] }, true)
      throw new Error('Select an operation.')
    },
    onSuccess: async () => { await onSaved(); close() },
  })
  function close() { setDialog(null); setProposedOfferingId(''); setAdjustedQuantity(String(order.lines.find((line) => line.id === originalLineId)?.remainingQuantity ?? '')); setAdjustmentReason(''); setShipmentQuantity(''); setCarrier(''); setService(''); setTrackingNumber(''); setLotBatchNumber(''); setExpiresAt(''); mutation.reset() }
  const mayPropose = ['Accepted', 'Processing', 'PartiallyShipped'].includes(order.status) && partnerOfferings.length > 0
    && order.lines.some((line) => line.shippedQuantity === 0 && line.cancelledQuantity === 0)
  const mayShip = ['Processing', 'PartiallyShipped'].includes(order.status) && order.lines.some((line) => line.remainingQuantity > 0)
  return <div className="mt-5 space-y-5"><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>Reagent fulfillment</CardTitle><CardDescription>Record approved commercial changes and shipment facts without rewriting the placement snapshot.</CardDescription></div><div className="flex gap-2">{mayPropose ? <Button type="button" variant="outline" onClick={() => setDialog('adjustment')}>Propose substitution</Button> : null}{mayShip ? <Button type="button" onClick={() => setDialog('shipment')}>Record shipment</Button> : null}</div></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="py-2 pr-3">Item</th><th className="px-3 py-2">Ordered</th><th className="px-3 py-2">Shipped</th><th className="px-3 py-2">Cancelled</th><th className="py-2 pl-3">Remaining</th></tr></thead><tbody>{order.lines.map((line) => <tr key={line.id} className="border-b last:border-0"><td className="py-3 pr-3">{line.description}</td><td className="px-3 py-3">{line.quantity}</td><td className="px-3 py-3">{line.shippedQuantity}</td><td className="px-3 py-3">{line.cancelledQuantity}</td><td className="py-2 pl-3">{line.remainingQuantity}</td></tr>)}</tbody></table></div></CardContent></Card><CancellationDecisionPanel workflowPath="reagent-orders" recordId={order.id} version={order.version} requests={order.cancellationRequests} reagentLines={order.lines} onSaved={onSaved} />
    <Dialog open={dialog === 'adjustment'} onOpenChange={(open) => !open && close()}><DialogContent><DialogHeader><DialogTitle>Propose reagent substitution</DialogTitle><DialogDescription>The Partner must explicitly approve the complete unfulfilled line and commercial effect before the substitute can be shipped.</DialogDescription></DialogHeader><div><Label htmlFor="adjustmentOriginalLine">Original line *</Label><select id="adjustmentOriginalLine" value={originalLineId} onChange={(event) => { const lineId = event.target.value; setOriginalLineId(lineId); setAdjustedQuantity(String(order.lines.find((line) => line.id === lineId)?.remainingQuantity ?? '')) }} className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm">{order.lines.filter((line) => line.shippedQuantity === 0 && line.cancelledQuantity === 0).map((line) => <option key={line.id} value={line.id}>{line.description}</option>)}</select></div><div><Label htmlFor="adjustmentOffering">Proposed Partner offering *</Label><select id="adjustmentOffering" value={proposedOfferingId} onChange={(event) => setProposedOfferingId(event.target.value)} className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="">Select offering</option>{partnerOfferings.map((offering) => <option key={offering.id} value={offering.id}>{offering.itemName} · {offering.currency} {offering.negotiatedUnitPrice.toFixed(2)}</option>)}</select></div><div><Label htmlFor="adjustmentQuantity">Substituted quantity</Label><Input id="adjustmentQuantity" type="number" className="mt-2" value={adjustedQuantity} readOnly /></div><div><Label htmlFor="adjustmentReason">Partner-visible reason *</Label><textarea id="adjustmentReason" value={adjustmentReason} onChange={(event) => setAdjustmentReason(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm" /></div>{mutation.error ? <Alert variant="destructive"><AlertTitle>Substitution was not proposed</AlertTitle><AlertDescription>{getOrderErrorMessage(mutation.error, 'Review the proposal and try again.')}</AlertDescription></Alert> : null}<DialogFooter><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button type="button" disabled={!proposedOfferingId || Number(adjustedQuantity) <= 0 || !adjustmentReason.trim() || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? 'Saving…' : 'Send for Partner approval'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={dialog === 'shipment'} onOpenChange={(open) => !open && close()}><DialogContent><DialogHeader><DialogTitle>Record reagent shipment</DialogTitle><DialogDescription>Each recorded shipment creates a separate QuickBooks invoice for its shipped quantities.</DialogDescription></DialogHeader><div><Label htmlFor="shipmentLine">Order line *</Label><select id="shipmentLine" value={shipmentLineId} onChange={(event) => setShipmentLineId(event.target.value)} className="mt-2 h-9 w-full rounded-lg border border-input bg-background px-3 text-sm">{order.lines.filter((line) => line.remainingQuantity > 0).map((line) => <option key={line.id} value={line.id}>{line.description} · {line.remainingQuantity} remaining</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="shipmentQuantity">Quantity *</Label><Input id="shipmentQuantity" type="number" step="any" max={selectedLine?.remainingQuantity} className="mt-2" value={shipmentQuantity} onChange={(event) => setShipmentQuantity(event.target.value)} /></div><div><Label htmlFor="shipmentLot">Lot or batch *</Label><Input id="shipmentLot" className="mt-2" value={lotBatchNumber} onChange={(event) => setLotBatchNumber(event.target.value)} /></div><div><Label htmlFor="shipmentCarrier">Carrier *</Label><Input id="shipmentCarrier" className="mt-2" value={carrier} onChange={(event) => setCarrier(event.target.value)} /></div><div><Label htmlFor="shipmentService">Service</Label><Input id="shipmentService" className="mt-2" value={service} onChange={(event) => setService(event.target.value)} /></div><div><Label htmlFor="shipmentTracking">Tracking number *</Label><Input id="shipmentTracking" className="mt-2" value={trackingNumber} onChange={(event) => setTrackingNumber(event.target.value)} /></div><div><Label htmlFor="shipmentShippedAt">Shipped at *</Label><Input id="shipmentShippedAt" type="datetime-local" className="mt-2" value={shippedAt} onChange={(event) => setShippedAt(event.target.value)} /></div><div><Label htmlFor="shipmentExpiration">Expiration date</Label><Input id="shipmentExpiration" type="date" className="mt-2" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></div></div>{mutation.error ? <Alert variant="destructive"><AlertTitle>Shipment was not recorded</AlertTitle><AlertDescription>{getOrderErrorMessage(mutation.error, 'Review the shipment and try again.')}</AlertDescription></Alert> : null}<DialogFooter><DialogClose asChild><Button type="button" variant="outline">Cancel</Button></DialogClose><Button type="button" disabled={Number(shipmentQuantity) <= 0 || Number(shipmentQuantity) > (selectedLine?.remainingQuantity ?? 0) || !carrier.trim() || !trackingNumber.trim() || !lotBatchNumber.trim() || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? 'Recording…' : 'Record shipment and invoice'}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
