import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { listCrmCompanies } from '#/api/crm'
import { getLabOperationsDashboard, labWorkOrderLabel } from '#/api/lab-operations'
import { listCommercialOrders, getOrderErrorMessage } from '#/api/order-management'
import { listOperationalAttention } from '#/api/pseq-order-to-cash'
import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'

export function ConnectedOperationsSummary({ section }: { section: 'orders' | 'lab' | 'accounts' }) {
  const orders = useQuery({ queryKey: ['commercial-orders', 'dashboard'], queryFn: () => listCommercialOrders({ activeIntake: true, pageSize: 5 }), enabled: section === 'orders' })
  const attention = useQuery({ queryKey: ['operational-attention', 'dashboard'], queryFn: () => listOperationalAttention(), enabled: section === 'orders' })
  const lab = useQuery({ queryKey: ['lab-operations'], queryFn: getLabOperationsDashboard, enabled: section === 'lab' })
  const companies = useQuery({ queryKey: ['crm', 'companies', 'dashboard'], queryFn: () => listCrmCompanies({ pageSize: 5 }), enabled: section === 'accounts' })
  const query = section === 'orders' ? orders : section === 'lab' ? lab : companies
  const work = lab.data?.workOrders.filter(item => !['Completed', 'Cancelled'].includes(item.status)) ?? []
  return <Card className={section === 'lab' ? 'gap-0 py-0' : undefined}><CardHeader className={section === 'lab' ? 'border-b bg-muted/50 p-4' : undefined}><CardTitle>{section === 'orders' ? 'Commercial work' : section === 'lab' ? 'Laboratory work' : 'Company access'}</CardTitle><CardDescription>{section === 'orders' ? 'Active intake and unresolved operational attention.' : section === 'lab' ? 'Authorized laboratory work and open exceptions.' : 'Open a Company to manage its people, services and readiness.'}</CardDescription>{section === 'lab' ? <CardAction><Button asChild><Link to="/lab-operations" search={{ section: undefined }}>Open Lab operations</Link></Button></CardAction> : null}</CardHeader><CardContent className={section === 'lab' ? 'space-y-4 p-4' : 'space-y-4'}>
    {query.isLoading ? <p role="status">Loading current work…</p> : null}
    {query.error ? <Alert variant="destructive"><AlertTitle>Current work could not be loaded</AlertTitle><AlertDescription>{getOrderErrorMessage(query.error, 'Try again.')} <Button variant="outline" onClick={() => void query.refetch()}>Retry</Button></AlertDescription></Alert> : null}
    {section === 'orders' && orders.data ? <><p>{orders.data.totalCount} orders in active intake · {attention.data ? `${attention.data.length} unresolved attention items` : attention.isError ? 'Attention unavailable' : 'Checking attention…'}</p>{attention.isError ? <Button variant="outline" onClick={() => void attention.refetch()}>Retry attention</Button> : null}<div className="divide-y">{orders.data.items.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><Link className="font-medium text-primary hover:underline" to="/order-operations/$workflow/$orderId" params={{ workflow: item.orderType === 'PSeqKit' ? 'reagent' : item.orderType === 'DataAssembly' ? 'assembly' : 'lab', orderId: item.id }}>{item.reference || item.number}</Link><Badge variant="outline">{item.status.replace(/([a-z])([A-Z])/g, '$1 $2')}</Badge></div>)}</div>{orders.data.items.length === 0 ? <p className="text-sm text-muted-foreground">No orders need commercial intake.</p> : null}<div className="flex flex-wrap gap-2"><Button asChild><Link to="/order-operations" search={{ orderSection: 'intake' }}>Open Intake</Link></Button><Button asChild variant="outline"><Link to="/order-operations" search={{ orderSection: 'intake', intakeView: 'holds' }}>Review holds</Link></Button><Button asChild variant="outline"><Link to="/order-operations" search={{ orderSection: 'attention' }}>Attention queue</Link></Button></div></> : null}
    {section === 'lab' && lab.data ? <><p>{work.length} active work orders · {work.reduce((total, item) => total + item.openExceptionCount, 0)} open exceptions</p><ul aria-label="Active laboratory work orders" className="space-y-3">{work.slice().sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5).map(item => <li key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-background p-4 shadow-xs"><Link className="min-w-0 wrap-anywhere font-medium text-primary hover:underline" to="/lab-operations/$workOrderId" params={{ workOrderId: item.id }} search={{ section: undefined }}>{labWorkOrderLabel(item)}</Link><span className="text-sm">{item.specimenCount} specimens · {item.status}</span></li>)}</ul>{work.length === 0 ? <p className="text-sm text-muted-foreground">No active laboratory work.</p> : null}</> : null}
    {section === 'accounts' && companies.data ? <><p>{companies.data.totalCount} Companies</p><div className="divide-y">{companies.data.items.map(item => <div key={item.id} className="flex flex-wrap justify-between gap-2 py-3"><Link className="font-medium text-primary hover:underline" to="/crm/companies/$companyId" params={{ companyId: item.id }}>{item.name}</Link><span className="text-sm">{item.portalRelationship ?? 'CRM only'} · {item.portalAccessStatus === 'Enabled' ? 'Portal enabled' : item.portalAccessStatus === 'Suspended' ? 'Portal suspended' : 'Portal not enabled'}</span></div>)}</div>{companies.data.items.length === 0 ? <p>No Companies yet.</p> : null}<div className="flex flex-wrap gap-2"><Button asChild><Link to="/crm/companies">Companies</Link></Button><Button asChild variant="outline"><Link to="/customers">Access requests</Link></Button></div></> : null}
  </CardContent></Card>
}
