import { useRef, useState } from 'react'
import type { TrialConfiguration } from '#/api/trials'
import { apiErrorMessage } from '#/api/organization-management'
import { Button } from '#/components/ui/button'
import { ActionMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '#/components/ui/dropdown-menu'
import { TrialFormDialog, type TrialFormField } from './TrialFormDialog'
import { useTrialMutation, useTrialQueries } from './trial-hooks'
import { trialChoices, trialDate, trialLabel } from './trial-presentation'

type ConfigurationAction = { title: string; description: string; path: string; fields: TrialFormField[]; payload?: (values: Record<string, string>) => object }
const reason: TrialFormField = { name: 'reason', label: 'Reason', type: 'textarea', required: true }
const assignmentNote: TrialFormField = { name: 'reason', label: 'Note (optional)', type: 'textarea' }
export function TrialConfigurationPanel() {
  const queries = useTrialQueries(); const mutation = useTrialMutation<TrialConfiguration>()
  const [action, setAction] = useState<ConfigurationAction | null>(null)
  const menuOpen = useRef(false)
  const trigger = useRef<HTMLButtonElement>(null)
  const selected = useRef<(() => void) | null>(null)
  function selectAction(run: () => void) { if (menuOpen.current) selected.current = run; else run() }
  if (!queries.staff) return <p className="p-6">Trial configuration requires Phaeno access.</p>
  const config = queries.config.data
  const configurationError = queries.config.error ? <div role="alert" className="space-y-2"><p>{apiErrorMessage(queries.config.error)}</p><Button variant="outline" disabled={queries.config.isFetching} onClick={() => { void queries.config.refetch() }}>{queries.config.isFetching ? 'Retrying…' : 'Retry configuration'}</Button></div> : null
  if (!config && configurationError) return <div className="space-y-4">{configurationError}</div>
  if (!config) return <p role="status" className="p-6">Loading Trial configuration…</p>
  function assign(primary: boolean) {
    setAction({ title: primary ? 'Assign primary approver' : 'Designate approval delegate', description: primary ? 'Assign Scientific Operations responsibility for Trial catalog and laboratory controls. Commercial leadership approves Trial scopes through its business role.' : 'A primary approver may explicitly delegate their own approval responsibility. Revocation preserves past decisions.', path: '/configuration/authorities', fields: [{ name: 'userId', label: 'Phaeno user', type: 'select', required: true, options: trialChoices(config!.staff) }, { name: 'domain', label: 'Approval responsibility', type: 'select', required: true, options: (primary ? ['ScientificOperations'] : config!.primaryDomains.filter(domain => domain === 'ScientificOperations')).map(value => ({ value, label: trialLabel(value) })) }, assignmentNote], payload: values => ({ ...values, isPrimary: primary }) })
  }
  return <section aria-label="Trial configuration" className="space-y-6"><header><h2 className="text-2xl font-semibold">Trial configuration</h2><p className="text-sm text-muted-foreground">Named approval responsibilities and versioned deliverables for no-charge PSeq evaluations.</p></header>
    {configurationError}
    <section className="space-y-4 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Approval authorities</h2><ActionMenu onOpenChange={opened => { menuOpen.current = opened }}><DropdownMenuTrigger asChild><Button ref={trigger} variant="outline">Actions</Button></DropdownMenuTrigger><DropdownMenuContent align="end" onCloseAutoFocus={event => { event.preventDefault(); trigger.current?.focus(); const run = selected.current; selected.current = null; run?.() }}>{config.canAssignPrimary ? <DropdownMenuItem onSelect={() => selectAction(() => assign(true))}>Assign primary</DropdownMenuItem> : null}{config.primaryDomains.includes('ScientificOperations') ? <DropdownMenuItem onSelect={() => selectAction(() => assign(false))}>Designate delegate</DropdownMenuItem> : null}</DropdownMenuContent></ActionMenu></div><p className="text-sm">Commercial leadership approval is granted through Phaeno user management. Assign Scientific Operations responsibility here for laboratory controls and the deliverable catalog; it is not a Trial scope approval.</p>
      <ul className="divide-y">{config.authorities.map(authority => <li key={authority.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{authority.userName}</p><p className="text-sm text-muted-foreground">{trialLabel(authority.domain)} · {authority.isPrimary ? 'Primary' : 'Delegate'} · {authority.revokedAtUtc ? `Revoked ${trialDate(authority.revokedAtUtc)}` : 'Active'}</p><p className="text-sm text-muted-foreground">Effective {trialDate(authority.effectiveAtUtc)} · Designated by {config.staff.find(user => user.id === authority.designatedByUserId)?.name ?? authority.designatedByUserId}. {authority.reason}{authority.revocationReason ? ` · Revocation: ${authority.revocationReason}` : ''}</p></div>{!authority.revokedAtUtc && (authority.isPrimary ? config.canAssignPrimary : config.primaryDomains.includes(authority.domain)) ? <Button variant="outline" size="sm" onClick={() => setAction({ title: 'Revoke approval authority', description: 'The user can no longer approve new Trial decisions under this authority. Revoking a primary also revokes their delegates. Past decisions remain intact.', path: `/configuration/authorities/${authority.id}/revoke`, fields: [reason], payload: values => ({ ...values, version: authority.version }) })}>Revoke</Button> : null}</li>)}</ul>
    </section>
    <section className="space-y-4 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Deliverable catalog</h2>{config.canManageConfiguration ? <Button variant="outline" onClick={() => setAction({ title: 'Define deliverable revision', description: 'Saving an existing key creates a new revision and retires its prior definition. Approved Trial scopes retain their frozen definitions.', path: '/configuration/deliverables', fields: [{ name: 'key', label: 'Deliverable key', required: true, help: 'For example FASTQ, FASTA, or BAM. Must match the scientific output role.' }, { name: 'name', label: 'Display name', required: true }, { name: 'isDefault', label: 'Select by default for new Trial scopes', type: 'select', required: true, options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] }, reason], payload: values => ({ ...values, isDefault: values.isDefault === 'yes' }) })}>Define revision</Button> : null}</div><ul className="divide-y">{config.deliverables.map(value => <li key={value.id} className="flex flex-wrap justify-between gap-3 py-3"><span>{value.name} · {value.key} · revision {value.revision}{config.defaultDeliverableIds.includes(value.id) ? ' · Default' : ''}</span>{config.canManageConfiguration ? <Button variant="outline" size="sm" onClick={() => setAction({ title: 'Retire deliverable', description: 'This definition will no longer be available for new scopes. Approved Trial scopes keep their frozen deliverables.', path: `/configuration/deliverables/${value.id}/retire`, fields: [reason] })}>Retire</Button> : null}</li>)}</ul></section>
    {action ? <TrialFormDialog title={action.title} description={action.description} fields={action.fields} onClose={() => setAction(null)} onSubmit={async (values, key) => { await mutation.mutateAsync({ path: action.path, payload: action.payload?.(values) ?? values, key }) }} /> : null}
  </section>
}
