import { Link } from '@tanstack/react-router'
import { useState } from 'react'
import type { TrialConfiguration } from '#/api/trials'
import { apiErrorMessage } from '#/api/organization-management'
import { Button } from '#/components/ui/button'
import { TrialFormDialog, type TrialFormField } from './TrialFormDialog'
import { useTrialMutation, useTrialQueries } from './trial-hooks'
import { trialChoices, trialDate, trialLabel } from './trial-presentation'

type ConfigurationAction = { title: string; description: string; path: string; fields: TrialFormField[]; payload?: (values: Record<string, string>) => object }
const reason: TrialFormField = { name: 'reason', label: 'Reason', type: 'textarea', required: true }
export function TrialConfigurationPage() {
  const queries = useTrialQueries(); const mutation = useTrialMutation<TrialConfiguration>()
  const [action, setAction] = useState<ConfigurationAction | null>(null)
  if (!queries.staff) return <p className="p-6">Trial configuration requires Phaeno access.</p>
  const config = queries.config.data
  if (queries.config.error) return <p role="alert" className="p-6">{apiErrorMessage(queries.config.error)}</p>
  if (!config) return <p role="status" className="p-6">Loading Trial configuration…</p>
  function assign(primary: boolean) {
    setAction({ title: primary ? 'Assign primary approver' : 'Designate approval delegate', description: primary ? 'The Commercial and Scientific Operations responsibilities remain separate. Two different people must approve each Trial scope.' : 'A primary approver may explicitly delegate their own approval responsibility. Revocation preserves past decisions.', path: '/configuration/authorities', fields: [{ name: 'userId', label: 'Phaeno user', type: 'select', required: true, options: trialChoices(config!.staff) }, { name: 'domain', label: 'Approval responsibility', type: 'select', required: true, options: (primary ? ['Commercial', 'ScientificOperations'] : config!.primaryDomains).map(value => ({ value, label: trialLabel(value) })) }, reason], payload: values => ({ ...values, isPrimary: primary }) })
  }
  return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-6"><Link to="/trial-projects" className="text-primary underline">Back to Trial projects</Link><header><h1 className="text-2xl font-semibold">Trial configuration</h1><p className="text-sm text-muted-foreground">Named approval responsibilities and versioned deliverables for no-charge PSeq evaluations.</p></header>
    <section className="space-y-4 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Approval authorities</h2><div className="flex flex-wrap gap-2">{config.canAssignPrimary ? <Button onClick={() => assign(true)}>Assign primary</Button> : null}{config.primaryDomains.length ? <Button variant="outline" onClick={() => assign(false)}>Designate delegate</Button> : null}</div></div><p className="text-sm">Commercial approval normally belongs to the CBO; Scientific Operations approval normally belongs to the COO. Assign the actual responsible users here.</p>
      <ul className="divide-y">{config.authorities.map(authority => <li key={authority.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{authority.userName}</p><p className="text-sm text-muted-foreground">{trialLabel(authority.domain)} · {authority.isPrimary ? 'Primary' : 'Delegate'} · {authority.revokedAtUtc ? `Revoked ${trialDate(authority.revokedAtUtc)}` : 'Active'}</p><p className="text-sm text-muted-foreground">Effective {trialDate(authority.effectiveAtUtc)} · Designated by {config.staff.find(user => user.id === authority.designatedByUserId)?.name ?? authority.designatedByUserId}. {authority.reason}{authority.revocationReason ? ` · Revocation: ${authority.revocationReason}` : ''}</p></div>{!authority.revokedAtUtc && (authority.isPrimary ? config.canAssignPrimary : config.primaryDomains.includes(authority.domain)) ? <Button variant="outline" size="sm" onClick={() => setAction({ title: 'Revoke approval authority', description: 'The user can no longer approve new Trial decisions under this authority. Revoking a primary also revokes their delegates. Past decisions remain intact.', path: `/configuration/authorities/${authority.id}/revoke`, fields: [reason], payload: values => ({ ...values, version: authority.version }) })}>Revoke</Button> : null}</li>)}</ul>
    </section>
    <section className="space-y-4 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">Deliverable catalog</h2>{config.canManageConfiguration ? <Button variant="outline" onClick={() => setAction({ title: 'Define deliverable revision', description: 'Saving an existing key creates a new revision and retires its prior definition. Approved Trial scopes retain their frozen definitions.', path: '/configuration/deliverables', fields: [{ name: 'key', label: 'Deliverable key', required: true, help: 'For example FASTQ, FASTA, or BAM. Must match the scientific output role.' }, { name: 'name', label: 'Display name', required: true }, { name: 'isDefault', label: 'Select by default for new Trial scopes', type: 'select', required: true, options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] }, reason], payload: values => ({ ...values, isDefault: values.isDefault === 'yes' }) })}>Define revision</Button> : null}</div><ul className="divide-y">{config.deliverables.map(value => <li key={value.id} className="flex flex-wrap justify-between gap-3 py-3"><span>{value.name} · {value.key} · revision {value.revision}{config.defaultDeliverableIds.includes(value.id) ? ' · Default' : ''}</span>{config.canManageConfiguration ? <Button variant="outline" size="sm" onClick={() => setAction({ title: 'Retire deliverable', description: 'This definition will no longer be available for new scopes. Approved Trial scopes keep their frozen deliverables.', path: `/configuration/deliverables/${value.id}/retire`, fields: [reason] })}>Retire</Button> : null}</li>)}</ul></section>
    {action ? <TrialFormDialog title={action.title} description={action.description} fields={action.fields} onClose={() => setAction(null)} onSubmit={async (values, key) => { await mutation.mutateAsync({ path: action.path, payload: action.payload?.(values) ?? values, key }) }} /> : null}
  </main>
}
