import { Link } from '@tanstack/react-router'
import { useRef, useState, type ReactNode } from 'react'
import { downloadTrial, type TrialConfiguration, type TrialDetail, type TrialScope } from '#/api/trials'
import { apiErrorMessage } from '#/api/organization-management'
import { Button } from '#/components/ui/button'
import { TrialSampleDialog } from './TrialSampleDialog'
import { ReleasedDeliverableRetentionNotice } from '#/features/orders/ReleasedDeliverableRetentionNotice'
import { TrialFormDialog, type TrialFormField } from './TrialFormDialog'
import { useTrialMutation, useTrialQueries } from './trial-hooks'
import { trialChoices, trialDate, trialLabel, trialTerminal, trialUtc } from './trial-presentation'

type Action = { title: string; description: string; path: string; fields: TrialFormField[]; payload?: (values: Record<string, string>, trial: TrialDetail) => object; content?: ReactNode; submitLabel?: string; blockedReason?: string; refresh?: (trial: TrialDetail, configuration?: TrialConfiguration) => Action }
type ActionFactory = (trial: TrialDetail, configuration?: TrialConfiguration) => Action
const reason: TrialFormField = { name: 'reason', label: 'Reason', type: 'textarea', required: true }
const safeReason: TrialFormField = { ...reason, label: 'Reason visible to the Prospect', help: 'Use clear, customer-safe wording without confidential laboratory or commercial details.' }
const select = (name: string, label: string, choices: string[]): TrialFormField => ({ name, label, type: 'select', required: true, options: choices.map(value => ({ value, label: trialLabel(value) })) })
export function TrialDetailPage({ trialId, fromCompanyId }: { trialId: string; fromCompanyId?: string }) {
  const queries = useTrialQueries(trialId); const mutation = useTrialMutation<TrialDetail>()
  const [action, setAction] = useState<Action | null>(null); const [downloadError, setDownloadError] = useState<string | null>(null)
  const [sampleDialog, setSampleDialog] = useState(false)
  const [transfer, setTransfer] = useState<{ name: string; percent: number | null } | null>(null)
  const currentTrial = useRef<TrialDetail | null>(null)
  const [selectedPackages, setSelectedPackages] = useState<string[]>([])
  const version = useRef<number | null>(null)
  if (!queries.allowed) return <p className="p-6">This Trial is unavailable in the selected organization and department.</p>
  if (queries.detail.error && !queries.detail.data) return <p role="alert" className="p-6">{apiErrorMessage(queries.detail.error)} <Button variant="outline" onClick={() => { void queries.detail.refetch() }}>Retry Trial</Button></p>
  const trial = queries.detail.data
  if (!trial) return <p role="status" className="p-6">Loading Trial…</p>
  const closed = trialTerminal(trial.status); const scientific = trial.approvalDomains.includes('ScientificOperations')
  const config = queries.config.data
  function open(build: ActionFactory) { version.current = trial!.version; currentTrial.current = trial!; setAction({ ...build(trial!, config), refresh: build }) }
  const act = (name: string, build: (trial: TrialDetail, configuration?: TrialConfiguration) => Omit<Action, 'path'>) => open((current, configuration) => ({ ...build(current, configuration), path: `/${trialId}/actions/${name}` }))
  async function download(path: string, name: string) {
    setDownloadError(null); setTransfer({ name, percent: null })
    try { await downloadTrial(`/${trialId}/results${path}`, name, percent => setTransfer({ name, percent })) }
    catch (failure) { setDownloadError(apiErrorMessage(failure)) }
    finally { setTransfer(null); await queries.detail.refetch() }
  }
  function acceptance(current: TrialDetail): Action {
    if (!current.scope || !current.canAccept) return { title: 'Review current Trial', description: 'Acceptance is no longer available for this Trial. Close this dialog to review its current status.', path: `/${trialId}/accept`, fields: [], blockedReason: 'Review the current Trial before continuing.', content: current.scope ? <TrialScopeView scope={current.scope} /> : null }
    return { title: 'Accept approved Trial scope', description: `Review scope revision ${current.scope!.revision}, including the allowance, submission window, deliverables, material handling, and terms.`, path: `/${trialId}/accept`,
      fields: [{ name: 'confirmed', label: 'I accept this Trial scope and confirm research use only with no PHI', type: 'checkbox', required: true }],
      payload: (values, latest) => ({ scopeRevision: latest.scope!.revision, termsVersion: latest.scope!.termsVersion, ruoNoPhiConfirmed: values.confirmed === 'yes' }), content: <TrialScopeView scope={current.scope!} />, submitLabel: 'Accept Trial scope', refresh: acceptance }
  }
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
    <Link to="/trial-projects" search={previous => ({ ...previous, fromCompanyId, requestId: undefined })} className="text-primary underline">Back to Trial projects</Link>
    {queries.detail.error ? <div role="alert" className="text-sm"><p>The Trial could not be refreshed. Your current workspace is preserved.</p><Button variant="outline" onClick={() => { void queries.detail.refetch() }}>Retry Trial refresh</Button></div> : null}
    {fromCompanyId && trial.isStaff ? <Link to="/crm/companies/$companyId" params={{ companyId: fromCompanyId }} className="ml-4 text-primary underline">Back to Company</Link> : null}
    <header className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-muted-foreground">{trial.companyName} · {trial.number}</p><h1 className="text-2xl font-semibold">{trial.scope?.name ?? 'Trial request'}</h1><p className="mt-1">{trialLabel(trial.status)}{trial.isOnHold ? ' · On hold' : ''} · No charge · Research use only</p></div><div className="flex flex-wrap gap-2 self-start">
      {trial.isStaff && !closed ? <Button asChild variant="outline"><Link to="/trial-projects/$trialId/scope" params={{ trialId }} search={previous => ({ ...previous, fromCompanyId, requestId: undefined })}> {trial.scope ? 'Amend scope' : 'Define scope'}</Link></Button> : null}
      {trial.canAccept ? <Button onClick={() => open(acceptance)}>Review and accept scope</Button> : null}
      {trial.canSubmit ? <Button disabled={!config} onClick={() => setSampleDialog(true)}>Submit samples</Button> : null}
      {trial.canSubmit && queries.config.error ? <p role="alert">Sample requirements could not load. <Button variant="outline" onClick={() => { void queries.config.refetch() }}>Retry sample requirements</Button></p> : null}
    </div></header>
    {trial.isOnHold ? <p role="status" className="rounded-lg border border-amber-500 p-4">On hold: {trial.holdReason}</p> : null}
    {trial.closureReason ? <p className="rounded-lg border p-4">Closed {trialDate(trial.closedAtUtc)}. {trial.closureReason}</p> : null}
    <section className="rounded-lg border p-4"><h2 className="mb-3 text-lg font-semibold">Scope and acceptance</h2>{trial.scope ? <TrialScopeView scope={trial.scope} /> : <p>The scientific scope has not been proposed.</p>}
      {trial.scope ? <p className="mt-3 text-sm">Approved revision: {trial.approvedScopeRevision ?? 'Awaiting approval'} · Accepted revision: {trial.acceptedScopeRevision ?? 'Awaiting acceptance'}</p> : null}
      {trial.isStaff && trial.status === 'UnderReview' && trial.approvalDomains.length ? <Button className="mt-4" onClick={() => open((trial) => ({ title: 'Record approval decision', description: 'Commercial and Scientific Operations approvals must come from different people. Changes require a new scope revision.', path: `/${trialId}/decisions`, fields: [select('domain', 'Approval responsibility', trial.approvalDomains), select('decision', 'Decision', ['Approve', 'RequestChanges', 'Decline']), reason] }))}>Record decision</Button> : null}
      {trial.scopeHistory.filter(value => value.revision !== trial.scope?.revision).map(scope => <details key={scope.revision} className="mt-4 border-t pt-3"><summary className="cursor-pointer font-medium">Previous scope · revision {scope.revision}</summary><div className="mt-3"><TrialScopeView scope={scope} /></div></details>)}
    </section>
    <section className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-semibold">Samples and laboratory progress</h2><Button asChild variant="outline" size="sm"><Link to="/sample-shipping">Shipping and packets</Link></Button></div><p className="text-sm">{trial.originalSamplesRemaining} original sample slots remain. {trial.scheduleEstimate ? `Schedule estimate: ${trial.scheduleEstimate}` : 'A schedule estimate has not been recorded.'}</p>
      {!trial.isStaff && trial.submissionBlocker ? <p className="text-sm text-muted-foreground">{trial.submissionBlocker}</p> : null}
      {trial.samples.length ? <ul className="divide-y">{trial.samples.map(sample => <li key={sample.id} className="space-y-1 py-3"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium">{sample.reference}{sample.replacesSampleId ? ' · Replacement' : ''}</span><span className="text-sm">{trialLabel(sample.labMilestone ?? sample.status)}</span></div><p className="text-sm text-muted-foreground">{sample.biologicalSource} · {sample.tubeCount} tubes · {trialDate(sample.submittedAtUtc)}</p><p className="text-sm">{sample.customerSafeSummary ?? sample.outcomeReason}</p>{sample.labWorkOrderId ? <Link to="/lab-operations/$workOrderId" search={{ section: "work" }} params={{ workOrderId: sample.labWorkOrderId }} className="text-sm text-primary underline">Open laboratory work</Link> : null}</li>)}</ul> : <p className="text-sm text-muted-foreground">No samples submitted.</p>}
    </section>
    <section className="space-y-3 rounded-lg border p-4"><h2 className="text-lg font-semibold">Results</h2><p className="text-sm text-muted-foreground">Partial releases may arrive as samples finish. The download retention period begins only when the complete approved Trial package is released.</p>{transfer ? <p role="status" className="text-sm">Downloading {transfer.name}{transfer.percent !== null ? ` ... ${transfer.percent}%` : '...'}</p> : null}{downloadError ? <div role="alert" className="space-y-2 text-destructive"><p>{downloadError}</p><Button variant="outline" onClick={() => { void queries.detail.refetch() }}>Refresh results and access</Button></div> : null}
      {trial.releases.length ? trial.releases.map(release => <article id={`trial-release-${release.id}`} key={release.id} className="space-y-2 border-t pt-3"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">Release {release.releaseVersion} · {release.isCompletePackage ? 'Complete Trial package' : 'Partial package'}{release.isWithdrawn ? ' · Withdrawn' : ''}</h3><span className="text-sm text-muted-foreground">{trialDate(release.releasedAtUtc)}</span></div>{release.downloadUnavailableReason ? <p className="text-sm text-muted-foreground">{release.downloadUnavailableReason}</p> : null}{!release.isCompletePackage && trial.releases.some(value => value.isCompletePackage) ? <a href={`#trial-release-${trial.releases.find(value => value.isCompletePackage)!.id}`} className="text-sm text-primary underline">Open complete Trial package</a> : null}<ReleasedDeliverableRetentionNotice retention={release.retention} /><ul className="space-y-1">{release.files.map(file => <li key={file.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="break-all">{file.fileName} · {file.fileKind}</span>{release.isDownloadAvailable && !trial.isStaff && !release.isWithdrawn && !trial.isOnHold && (!trial.releases.some(value => value.isCompletePackage) || release.isCompletePackage) ? <Button variant="ghost" size="sm" disabled={Boolean(transfer)} onClick={() => { void download(`/files/${file.id}/download`, file.fileName) }}>Download {file.fileKind}</Button> : null}</li>)}</ul><div className="flex flex-wrap gap-2">{release.isDownloadAvailable && !trial.isStaff && !release.isWithdrawn && !trial.isOnHold && (!trial.releases.some(value => value.isCompletePackage) || release.isCompletePackage) ? <Button variant="outline" size="sm" disabled={Boolean(transfer)} onClick={() => { void download(`/releases/${release.id}/download`, `${trial.number}-release-${release.releaseVersion}.zip`) }}>Download package</Button> : null}{release.retentionSnapshotId ? <Button asChild variant="outline" size="sm"><Link to="/released-deliverables/$snapshotId" search={{ q: "", page: 0 }} params={{ snapshotId: release.retentionSnapshotId }}>Retention and receipt</Link></Button> : null}{trial.canReleaseResults && !release.isWithdrawn ? <Button variant="outline" size="sm" onClick={() => open(() => ({ title: 'Withdraw Trial release', description: 'Withdrawals revoke delivery and retain the audit history. Release-manager authority is required.', path: `/${trialId}/results/releases/${release.id}/withdraw`, fields: [safeReason] }))}>Withdraw release</Button> : null}</div></article>) : <p className="text-sm">No results released yet.</p>}
      {trial.canReleaseResults ? <details className="border-t pt-3"><summary className="cursor-pointer font-medium">Scientific review and release</summary><p className="mt-2 text-sm">Select one scientifically approved output package per sample. Complete releases must contain all successful samples. Release-manager authority and enabled governed storage are required.</p>{queries.packages.error ? <p role="alert">{apiErrorMessage(queries.packages.error)}</p> : null}<div className="my-3 space-y-2">{queries.packages.data?.map(value => <label key={value.id} className="flex cursor-pointer items-start gap-2 text-sm"><input type="checkbox" className="mt-1 size-4 accent-primary" checked={selectedPackages.includes(value.id)} onChange={event => setSelectedPackages(previous => event.target.checked ? [...previous, value.id] : previous.filter(id => id !== value.id))} />{trial.samples.find(sample => sample.id === value.trialSampleId)?.reference ?? 'Sample'} · package {value.packageVersion} · {trialLabel(value.state)}{value.scientificApprovalId ? ' · Scientific approval recorded' : ' · Awaiting scientific approval'}</label>)}</div><Button variant="outline" disabled={!selectedPackages.length || trial.isOnHold} onClick={() => open((trial) => ({ title: 'Release Trial results', description: 'A complete package closes the Trial and freezes its download retention policy. A partial package leaves the retention clock unstarted.', path: `/${trialId}/results/release`, fields: [select('kind', 'Package coverage', ['Partial', 'Complete']), ...(trial.status === 'Completed' ? [{ name: 'supersedesReleaseId', label: 'Deleted release being reissued', type: 'select' as const, required: true, options: trial.releases.filter(value => value.isCompletePackage).map(value => ({ value: value.id, label: `Release ${value.releaseVersion}` })) }] : []), safeReason], payload: values => ({ outputPackageIds: selectedPackages, completePackage: values.kind === 'Complete', reason: values.reason, supersedesReleaseId: values.supersedesReleaseId || null }) }))}>Release selected results</Button></details> : null}
    </section>
    {trial.isStaff ? <section className="space-y-3 rounded-lg border p-4"><h2 className="text-lg font-semibold">Trial management</h2>{trial.crmPendingMilestones ? <div role="status" className="space-y-2 text-sm"><p>{trial.crmPendingMilestones} CRM milestones are awaiting publication. Trial operations remain available.</p><Button variant="outline" onClick={() => open(() => ({ title: "Retry CRM milestones", description: "Publish pending relationship-safe milestones to the CRM company and opportunity.", path: `/${trialId}/crm/retry`, fields: [] }))}>Retry CRM publication</Button></div> : null}<div className="flex flex-wrap gap-2">
      {!closed ? <Button variant="outline" onClick={() => act('schedule', (trial) => ({ title: 'Update schedule estimate', description: 'This estimate is visible to the Prospect; it is not a guaranteed turnaround time.', fields: [{ name: 'scheduleEstimate', label: 'Schedule estimate', required: true, type: 'textarea', defaultValue: trial.scheduleEstimate ?? '' }, reason] }))}>Schedule estimate</Button> : null}
      {scientific ? <Button variant="outline" onClick={() => act('hold', (trial) => ({ title: trial.isOnHold ? 'Release Trial hold' : 'Place Trial on hold', description: 'A hold stops new submissions, scientific progress, result delivery, and residual disposition.', fields: [safeReason], payload: (values, latest) => ({ ...values, hold: !latest.isOnHold }) }))}>{trial.isOnHold ? 'Release hold' : 'Place hold'}</Button> : null}
      {scientific && !closed && trial.samples.length ? <Button variant="outline" onClick={() => act('replacement', (trial) => ({ title: 'Authorize replacement sample', description: 'Record the failed original sample and the cause. Each authorization permits one replacement without changing the original allowance.', fields: [{ name: 'sampleId', label: 'Failed sample', type: 'select', required: true, options: trial.samples.filter(sample => !trial.replacements.some(value => value.originalSampleId === sample.id)).map(sample => ({ value: sample.id, label: sample.reference })) }, select('cause', 'Failure responsibility', ['Phaeno', 'Prospect']), safeReason], payload: values => ({ sampleId: values.sampleId, phaenoCausedFailure: values.cause === 'Phaeno', reason: values.reason }) }))}>Authorize replacement</Button> : null}
      {scientific && !closed ? <Button variant="outline" onClick={() => act('close', (trial) => ({ title: 'Close Trial', description: 'Use a complete result release for successful completion. Other closures retain the scope, samples, and audit history.', fields: [select('closureStatus', 'Closure outcome', ['ClosedIncomplete', 'Cancelled', 'Expired', ...(!trial.samples.length ? ['Declined'] : [])]), safeReason] }))}>Close Trial</Button> : null}
      {scientific && closed && !trial.actualMaterialDisposition ? <Button variant="outline" onClick={() => act('material', (trial) => ({ title: 'Record residual material disposition', description: `Retention until: ${trialDate(trial.residualRetainUntilUtc)}. Record the actual completed disposition under the frozen material terms.`, fields: [select('materialDisposition', 'Actual disposition', [trial.scope?.materialDisposition === 'Return' ? 'Returned' : 'Destroyed', 'Exhausted']), safeReason] }))}>Record material disposition</Button> : null}
      {trial.canRecordCommercialOutcome ? <Button variant="outline" onClick={() => act('commercial-outcome', (_trial, config) => ({ title: 'Record commercial outcome', description: 'Commercial follow-up is separate from scientific completion. Conversion must first be completed through the CRM relationship workflow.', fields: [select('commercialOutcome', 'Commercial outcome', ['FollowUpScheduled', 'ConvertedToCustomer', 'ConvertedToPartner', 'ClosedWithoutConversion']), { name: 'followUpOwnerUserId', label: 'Follow-up owner', type: 'select', options: trialChoices(config?.staff) }, { name: 'followUpAtUtc', label: 'Follow-up date', type: 'datetime-local' }, reason], payload: values => ({ ...values, followUpOwnerUserId: values.followUpOwnerUserId || null, followUpAtUtc: trialUtc(values.followUpAtUtc) }) }))}>Commercial outcome</Button> : null}
      {trial.canDeactivateProspect ? <Button variant="outline" onClick={() => act('deactivate-prospect', () => ({ title: 'Close Prospect access', description: 'This deactivates the Prospect company and Portal access. All Trials and commercial evaluations must be closed, with no holds, open Opportunities, active grants, or service access. Trial history and existing retention deadlines remain.', fields: [reason], submitLabel: 'Deactivate Prospect' }))}>Close Prospect access</Button> : null}
    </div><p className="text-sm">{trial.commercialOutcome ? `${trialLabel(trial.commercialOutcome)} · ${trial.commercialOutcomeReason}` : 'Commercial outcome not yet recorded.'}</p>{trial.actualMaterialDisposition ? <p className="text-sm">Residual material: {trial.actualMaterialDisposition}</p> : null}</section> : null}
    <section className="rounded-lg border p-4"><h2 className="mb-3 text-lg font-semibold">Timeline</h2><ol className="space-y-3">{trial.timeline.map((event, index) => <li key={`${event.atUtc}-${index}`} className="text-sm"><p>{event.summary}</p><time className="text-xs text-muted-foreground" dateTime={event.atUtc}>{trialDate(event.atUtc)}</time></li>)}</ol></section>
    {sampleDialog && config ? <TrialSampleDialog trial={trial} configuration={config} onClose={() => setSampleDialog(false)} onReload={async () => {
      const [detail, configuration] = await Promise.all([queries.detail.refetch(), queries.config.refetch()]); if (detail.error) throw detail.error; if (configuration.error) throw configuration.error; return { trial: detail.data!, configuration: configuration.data! }
    }} onSubmit={async (payload, key) => mutation.mutateAsync({ path: `/${trialId}/samples`, payload, key })} /> : null}
    {action ? <TrialFormDialog title={action.title} description={action.description} fields={action.fields} submitLabel={action.submitLabel} submitDisabled={Boolean(action.blockedReason)} onClose={() => setAction(null)} onReload={async () => {
      const [refreshed, configuration] = await Promise.all([queries.detail.refetch(), queries.config.refetch()]); if (refreshed.error) throw refreshed.error; if (configuration.error) throw configuration.error
      const latest = refreshed.data!; const previous = currentTrial.current!; version.current = latest.version; currentTrial.current = latest
      const next = { ...action.refresh!(latest, configuration.data), refresh: action.refresh }
      if (action.path.endsWith('/results/release')) {
        const packages = await queries.packages.refetch(); if (packages.error) throw packages.error
        if (selectedPackages.some(id => !packages.data?.some(value => value.id === id && value.scientificApprovalId))) next.blockedReason = 'Selected output packages changed. Close this dialog and review the current scientific packages before release.'
      }
      setAction(next)
      return { fields: next.fields, resetFields: previous.scope?.revision !== latest.scope?.revision || previous.scope?.termsVersion !== latest.scope?.termsVersion ? ['confirmed'] : [], message: next.blockedReason ?? (action.path.endsWith('/accept') ? 'The approved scope was refreshed. Review the current scope and confirm acceptance again if its revision changed.' : 'The current Trial and available choices were refreshed. Your valid entries are preserved; review them before saving.') }
    }} onSubmit={async (values, key) => { await mutation.mutateAsync({ path: action.path, payload: { ...(action.payload?.(values, currentTrial.current!) ?? values), version: version.current }, key }) }}>{action.content}</TrialFormDialog> : null}
  </main>
}
export function TrialScopeView({ scope }: { scope: TrialScope }) {
  return <div className="space-y-3 text-sm"><p className="whitespace-pre-wrap">{scope.objective}</p><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-muted-foreground">Original sample allowance</dt><dd>{scope.sampleAllowance}</dd></div><div><dt className="text-muted-foreground">Submission window</dt><dd>{trialDate(scope.submissionOpensAtUtc)} – {trialDate(scope.submissionClosesAtUtc)}</dd></div><div><dt className="text-muted-foreground">PSeq analyses</dt><dd>{scope.analyses.map(value => `${value.name} (v${value.version})`).join(', ')}</dd></div><div><dt className="text-muted-foreground">Deliverables</dt><dd>{scope.deliverables.map(value => value.name).join(', ')}</dd></div></dl><div><h3 className="font-medium">Submission instructions</h3><p className="whitespace-pre-wrap">{scope.submissionInstructions}</p>{scope.analyses.map(value => <p key={value.id} className="mt-2 whitespace-pre-wrap">{value.name}: {value.instructions}</p>)}</div><div><h3 className="font-medium">Acceptance criteria</h3><p className="whitespace-pre-wrap">{scope.successCriteria}</p></div><p>Residual RNA: retain {scope.residualRetentionDays} days after closure; {scope.materialDisposition === 'Return' ? `return to ${scope.returnDestination}; ${scope.returnHandling}; shipping payer: ${scope.returnShippingPayer}` : 'destroy after the retention period'}.</p><div><h3 className="font-medium">Terms · revision {scope.revision}</h3><p className="whitespace-pre-wrap">{scope.terms}</p><p className="mt-2 font-medium">{scope.ruoStatement}</p></div>{scope.internalValues ? <p className="text-muted-foreground">Internal only · Estimated retail value: {scope.internalValues.estimatedRetailValue} · Anticipated internal cost: {scope.internalValues.anticipatedInternalCost}</p> : null}{scope.decisions.length ? <ul>{scope.decisions.map(value => <li key={value.domain}>{trialLabel(value.domain)}: {trialLabel(value.decision)} · {trialDate(value.atUtc)}{value.reason ? ` · ${value.reason}` : ''}</li>)}</ul> : null}</div>
}
