import { Link } from '@tanstack/react-router'
import { useRef, useState, type ReactNode } from 'react'
import { downloadTrial, type TrialDetail, type TrialScope } from '#/api/trials'
import { apiErrorMessage } from '#/api/organization-management'
import { Button } from '#/components/ui/button'
import { TrialFormDialog, type TrialFormField } from './TrialFormDialog'
import { useTrialMutation, useTrialQueries } from './trial-hooks'
import { requiredTrialInputs, trialChoices, trialDate, trialLabel, trialTerminal, trialUtc } from './trial-presentation'

type Action = { title: string; description: string; path: string; fields: TrialFormField[]; payload?: (values: Record<string, string>) => object; content?: ReactNode; submitLabel?: string }
const reason: TrialFormField = { name: 'reason', label: 'Reason', type: 'textarea', required: true }
const safeReason: TrialFormField = { ...reason, label: 'Reason visible to the Prospect', help: 'Use clear, customer-safe wording without confidential laboratory or commercial details.' }
const select = (name: string, label: string, choices: string[]): TrialFormField => ({ name, label, type: 'select', required: true, options: choices.map(value => ({ value, label: trialLabel(value) })) })
export function TrialDetailPage({ trialId }: { trialId: string }) {
  const queries = useTrialQueries(trialId); const mutation = useTrialMutation<TrialDetail>()
  const [action, setAction] = useState<Action | null>(null); const [downloadError, setDownloadError] = useState<string | null>(null)
  const [selectedPackages, setSelectedPackages] = useState<string[]>([])
  const version = useRef<number | null>(null)
  if (!queries.allowed) return <p className="p-6">This Trial is unavailable in the selected organization and department.</p>
  if (queries.detail.error) return <p role="alert" className="p-6">{apiErrorMessage(queries.detail.error)}</p>
  const trial = queries.detail.data
  if (!trial) return <p role="status" className="p-6">Loading Trial…</p>
  const closed = trialTerminal(trial.status); const scientific = trial.approvalDomains.includes('ScientificOperations')
  const config = queries.config.data
  function open(value: Action) { version.current = trial!.version; setAction(value) }
  const act = (name: string, value: Omit<Action, 'path'>) => open({ ...value, path: `/${trialId}/actions/${name}` })
  async function download(path: string, name: string) { setDownloadError(null); try { await downloadTrial(`/${trialId}/results${path}`, name) } catch (failure) { setDownloadError(apiErrorMessage(failure)) } }
  function submitSample() {
    const extras = requiredTrialInputs(trial!.scope)
    const replacementOptions = trial!.replacements.filter(value => !value.usedBySampleId).map(value => ({ value: value.id, label: trial!.samples.find(sample => sample.id === value.originalSampleId)?.reference ?? 'Approved replacement' }))
    open({ title: 'Submit extracted RNA sample', description: 'Use a coded research sample reference. Do not enter patient identifiers, dates of birth, medical record numbers, or other PHI.', path: `/${trialId}/samples`, submitLabel: 'Submit sample',
      fields: [{ name: 'reference', label: 'Coded sample reference', required: true }, { name: 'biologicalSource', label: 'Biological source', required: true },
        { name: 'destinationId', label: 'Shipping destination', type: 'select', required: true, options: trialChoices(config?.destinations) }, { name: 'sampleTypeId', label: 'Extracted RNA sample type', type: 'select', required: true, options: trialChoices(config?.sampleTypes) },
        { name: 'tubeCount', label: 'Number of tubes', type: 'number', required: true, min: 1, defaultValue: '1' }, { name: 'quantity', label: 'Quantity', type: 'number', required: true, min: 0.001 }, { name: 'quantityUnit', label: 'Quantity unit', type: 'select', required: true, options: ['ng', 'ug', 'mg', 'ul', 'ml'].map(value => ({ value, label: value })) }, { name: 'concentration', label: 'Concentration (ng/µL)', type: 'number', min: 0.001 },
        { name: 'storageRequirements', label: 'Storage requirements', type: 'textarea', required: true }, { name: 'safetyDeclaration', label: 'Research material safety declaration', type: 'textarea', required: true },
        ...extras.map(name => ({ name: `input_${name}`, label: trialLabel(name), required: true })),
        ...(replacementOptions.length ? [{ name: 'replacementAuthorizationId', label: 'Approved replacement for', type: 'select' as const, required: trial!.originalSamplesRemaining === 0, options: replacementOptions }] : []),
        { name: 'ruo', label: 'I confirm research use only and no PHI or direct personal identifiers', type: 'checkbox', required: true }],
      payload: values => { const replacement = trial!.replacements.find(value => value.id === values.replacementAuthorizationId); return { destinationId: values.destinationId, sampleTypeId: values.sampleTypeId, ruoNoPhiConfirmed: values.ruo === 'yes', samples: [{ reference: values.reference, biologicalSource: values.biologicalSource, tubeCount: Number(values.tubeCount), quantity: Number(values.quantity), quantityUnit: values.quantityUnit, concentration: values.concentration ? Number(values.concentration) : null, storageRequirements: values.storageRequirements, safetyDeclaration: values.safetyDeclaration, inputs: Object.fromEntries(extras.map(name => [name, values[`input_${name}`]])), replacesSampleId: replacement?.originalSampleId ?? null, replacementAuthorizationId: replacement?.id ?? null }] } },
      content: <p className="whitespace-pre-wrap text-sm">{trial!.scope?.submissionInstructions}</p>,
    })
  }
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
    <Link to="/trial-projects" className="text-primary underline">Back to Trial projects</Link>
    <header className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-muted-foreground">{trial.companyName} · {trial.number}</p><h1 className="text-2xl font-semibold">{trial.scope?.name ?? 'Trial request'}</h1><p className="mt-1">{trialLabel(trial.status)}{trial.isOnHold ? ' · On hold' : ''} · No charge · Research use only</p></div><div className="flex flex-wrap gap-2 self-start">
      {trial.isStaff && !closed ? <Button asChild variant="outline"><Link to="/trial-projects/$trialId/scope" params={{ trialId }}> {trial.scope ? 'Amend scope' : 'Define scope'}</Link></Button> : null}
      {trial.canAccept ? <Button onClick={() => open({ title: 'Accept approved Trial scope', description: `Review scope revision ${trial.scope!.revision}, including the allowance, submission window, deliverables, material handling, and terms.`, path: `/${trialId}/accept`, fields: [{ name: 'confirmed', label: 'I accept this Trial scope and confirm research use only with no PHI', type: 'checkbox', required: true }], payload: values => ({ scopeRevision: trial.scope!.revision, termsVersion: trial.scope!.termsVersion, ruoNoPhiConfirmed: values.confirmed === 'yes' }), content: <TrialScopeView scope={trial.scope!} />, submitLabel: 'Accept Trial scope' })}>Review and accept scope</Button> : null}
      {trial.canSubmit ? <Button onClick={submitSample}>Submit sample</Button> : null}
    </div></header>
    {trial.isOnHold ? <p role="status" className="rounded-lg border border-amber-500 p-4">On hold: {trial.holdReason}</p> : null}
    {trial.closureReason ? <p className="rounded-lg border p-4">Closed {trialDate(trial.closedAtUtc)}. {trial.closureReason}</p> : null}
    <section className="rounded-lg border p-4"><h2 className="mb-3 text-lg font-semibold">Scope and acceptance</h2>{trial.scope ? <TrialScopeView scope={trial.scope} /> : <p>The scientific scope has not been proposed.</p>}
      {trial.scope ? <p className="mt-3 text-sm">Approved revision: {trial.approvedScopeRevision ?? 'Awaiting approval'} · Accepted revision: {trial.acceptedScopeRevision ?? 'Awaiting acceptance'}</p> : null}
      {trial.isStaff && trial.status === 'UnderReview' && trial.approvalDomains.length ? <Button className="mt-4" onClick={() => open({ title: 'Record approval decision', description: 'Commercial and Scientific Operations approvals must come from different people. Changes require a new scope revision.', path: `/${trialId}/decisions`, fields: [select('domain', 'Approval responsibility', trial.approvalDomains), select('decision', 'Decision', ['Approve', 'RequestChanges', 'Decline']), reason] })}>Record decision</Button> : null}
      {trial.scopeHistory.filter(value => value.revision !== trial.scope?.revision).map(scope => <details key={scope.revision} className="mt-4 border-t pt-3"><summary className="cursor-pointer font-medium">Previous scope · revision {scope.revision}</summary><div className="mt-3"><TrialScopeView scope={scope} /></div></details>)}
    </section>
    <section className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="text-lg font-semibold">Samples and laboratory progress</h2><Button asChild variant="outline" size="sm"><Link to="/sample-shipping">Shipping and packets</Link></Button></div><p className="text-sm">{trial.originalSamplesRemaining} original sample slots remain. {trial.scheduleEstimate ? `Schedule estimate: ${trial.scheduleEstimate}` : 'A schedule estimate has not been recorded.'}</p>
      {!trial.isStaff && trial.submissionBlocker ? <p className="text-sm text-muted-foreground">{trial.submissionBlocker}</p> : null}
      {trial.samples.length ? <ul className="divide-y">{trial.samples.map(sample => <li key={sample.id} className="space-y-1 py-3"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium">{sample.reference}{sample.replacesSampleId ? ' · Replacement' : ''}</span><span className="text-sm">{trialLabel(sample.labMilestone ?? sample.status)}</span></div><p className="text-sm text-muted-foreground">{sample.biologicalSource} · {sample.tubeCount} tubes · {trialDate(sample.submittedAtUtc)}</p><p className="text-sm">{sample.customerSafeSummary ?? sample.outcomeReason}</p>{sample.labWorkOrderId ? <Link to="/lab-operations/$workOrderId" search={{ section: "work" }} params={{ workOrderId: sample.labWorkOrderId }} className="text-sm text-primary underline">Open laboratory work</Link> : null}</li>)}</ul> : <p className="text-sm text-muted-foreground">No samples submitted.</p>}
    </section>
    <section className="space-y-3 rounded-lg border p-4"><h2 className="text-lg font-semibold">Results</h2><p className="text-sm text-muted-foreground">Partial releases may arrive as samples finish. The download retention period begins only when the complete approved Trial package is released.</p>{downloadError ? <p role="alert" className="text-destructive">{downloadError}</p> : null}
      {trial.releases.length ? trial.releases.map(release => <article key={release.id} className="space-y-2 border-t pt-3"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">Release {release.releaseVersion} · {release.isCompletePackage ? 'Complete Trial package' : 'Partial package'}{release.isWithdrawn ? ' · Withdrawn' : ''}</h3><span className="text-sm text-muted-foreground">{trialDate(release.releasedAtUtc)}</span></div><ul className="space-y-1">{release.files.map(file => <li key={file.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="break-all">{file.fileName} · {file.fileKind}</span>{!trial.isStaff && !release.isWithdrawn && !trial.isOnHold ? <Button variant="ghost" size="sm" onClick={() => { void download(`/files/${file.id}/download`, file.fileName) }}>Download {file.fileKind}</Button> : null}</li>)}</ul><div className="flex flex-wrap gap-2">{!trial.isStaff && !release.isWithdrawn && !trial.isOnHold ? <Button variant="outline" size="sm" onClick={() => { void download(`/releases/${release.id}/download`, `${trial.number}-release-${release.releaseVersion}.zip`) }}>Download package</Button> : null}{release.retentionSnapshotId ? <Button asChild variant="outline" size="sm"><Link to="/released-deliverables/$snapshotId" search={{ q: "", page: 0 }} params={{ snapshotId: release.retentionSnapshotId }}>Retention and receipt</Link></Button> : null}{trial.canReleaseResults && !release.isWithdrawn ? <Button variant="outline" size="sm" onClick={() => open({ title: 'Withdraw Trial release', description: 'Withdrawals revoke delivery and retain the audit history. Release-manager authority is required.', path: `/${trialId}/results/releases/${release.id}/withdraw`, fields: [safeReason] })}>Withdraw release</Button> : null}</div></article>) : <p className="text-sm">No results released yet.</p>}
      {trial.canReleaseResults ? <details className="border-t pt-3"><summary className="cursor-pointer font-medium">Scientific review and release</summary><p className="mt-2 text-sm">Select one scientifically approved output package per sample. Complete releases must contain all successful samples. Release-manager authority and enabled governed storage are required.</p>{queries.packages.error ? <p role="alert">{apiErrorMessage(queries.packages.error)}</p> : null}<div className="my-3 space-y-2">{queries.packages.data?.map(value => <label key={value.id} className="flex cursor-pointer items-start gap-2 text-sm"><input type="checkbox" className="mt-1 size-4 accent-primary" checked={selectedPackages.includes(value.id)} onChange={event => setSelectedPackages(previous => event.target.checked ? [...previous, value.id] : previous.filter(id => id !== value.id))} />{trial.samples.find(sample => sample.id === value.trialSampleId)?.reference ?? 'Sample'} · package {value.packageVersion} · {trialLabel(value.state)}{value.scientificApprovalId ? ' · Scientific approval recorded' : ' · Awaiting scientific approval'}</label>)}</div><Button variant="outline" disabled={!selectedPackages.length || trial.isOnHold} onClick={() => open({ title: 'Release Trial results', description: 'A complete package closes the Trial and freezes its download retention policy. A partial package leaves the retention clock unstarted.', path: `/${trialId}/results/release`, fields: [select('kind', 'Package coverage', ['Partial', 'Complete']), ...(trial.status === 'Completed' ? [{ name: 'supersedesReleaseId', label: 'Deleted release being reissued', type: 'select' as const, required: true, options: trial.releases.filter(value => value.isCompletePackage).map(value => ({ value: value.id, label: `Release ${value.releaseVersion}` })) }] : []), safeReason], payload: values => ({ outputPackageIds: selectedPackages, completePackage: values.kind === 'Complete', reason: values.reason, supersedesReleaseId: values.supersedesReleaseId || null }) })}>Release selected results</Button></details> : null}
    </section>
    {trial.isStaff ? <section className="space-y-3 rounded-lg border p-4"><h2 className="text-lg font-semibold">Trial management</h2>{trial.crmPendingMilestones ? <div role="status" className="space-y-2 text-sm"><p>{trial.crmPendingMilestones} CRM milestones are awaiting publication. Trial operations remain available.</p><Button variant="outline" onClick={() => open({ title: "Retry CRM milestones", description: "Publish pending relationship-safe milestones to the CRM company and opportunity.", path: `/${trialId}/crm/retry`, fields: [] })}>Retry CRM publication</Button></div> : null}<div className="flex flex-wrap gap-2">
      {!closed ? <Button variant="outline" onClick={() => act('schedule', { title: 'Update schedule estimate', description: 'This estimate is visible to the Prospect; it is not a guaranteed turnaround time.', fields: [{ name: 'scheduleEstimate', label: 'Schedule estimate', required: true, type: 'textarea', defaultValue: trial.scheduleEstimate ?? '' }, reason] })}>Schedule estimate</Button> : null}
      {scientific ? <Button variant="outline" onClick={() => act('hold', { title: trial.isOnHold ? 'Release Trial hold' : 'Place Trial on hold', description: 'A hold stops new submissions, scientific progress, result delivery, and residual disposition.', fields: [safeReason], payload: values => ({ ...values, hold: !trial.isOnHold }) })}>{trial.isOnHold ? 'Release hold' : 'Place hold'}</Button> : null}
      {scientific && !closed && trial.samples.length ? <Button variant="outline" onClick={() => act('replacement', { title: 'Authorize replacement sample', description: 'Record the failed original sample and the cause. Each authorization permits one replacement without changing the original allowance.', fields: [{ name: 'sampleId', label: 'Failed sample', type: 'select', required: true, options: trial.samples.filter(sample => !trial.replacements.some(value => value.originalSampleId === sample.id)).map(sample => ({ value: sample.id, label: sample.reference })) }, select('cause', 'Failure responsibility', ['Phaeno', 'Prospect']), safeReason], payload: values => ({ sampleId: values.sampleId, phaenoCausedFailure: values.cause === 'Phaeno', reason: values.reason }) })}>Authorize replacement</Button> : null}
      {scientific && !closed ? <Button variant="outline" onClick={() => act('close', { title: 'Close Trial', description: 'Use a complete result release for successful completion. Other closures retain the scope, samples, and audit history.', fields: [select('closureStatus', 'Closure outcome', ['ClosedIncomplete', 'Cancelled', 'Expired', ...(!trial.samples.length ? ['Declined'] : [])]), safeReason] })}>Close Trial</Button> : null}
      {scientific && closed && !trial.actualMaterialDisposition ? <Button variant="outline" onClick={() => act('material', { title: 'Record residual material disposition', description: `Retention until: ${trialDate(trial.residualRetainUntilUtc)}. Record the actual completed disposition under the frozen material terms.`, fields: [select('materialDisposition', 'Actual disposition', [trial.scope?.materialDisposition === 'Return' ? 'Returned' : 'Destroyed', 'Exhausted']), safeReason] })}>Record material disposition</Button> : null}
      {trial.canRecordCommercialOutcome ? <Button variant="outline" onClick={() => act('commercial-outcome', { title: 'Record commercial outcome', description: 'Commercial follow-up is separate from scientific completion. Conversion must first be completed through the CRM relationship workflow.', fields: [select('commercialOutcome', 'Commercial outcome', ['FollowUpScheduled', 'ConvertedToCustomer', 'ConvertedToPartner', 'ClosedWithoutConversion']), { name: 'followUpOwnerUserId', label: 'Follow-up owner', type: 'select', options: trialChoices(config?.staff) }, { name: 'followUpAtUtc', label: 'Follow-up date', type: 'datetime-local' }, reason], payload: values => ({ ...values, followUpOwnerUserId: values.followUpOwnerUserId || null, followUpAtUtc: trialUtc(values.followUpAtUtc) }) })}>Commercial outcome</Button> : null}
      {trial.canDeactivateProspect ? <Button variant="outline" onClick={() => act('deactivate-prospect', { title: 'Close Prospect access', description: 'This deactivates the Prospect company and Portal access. All Trials and commercial evaluations must be closed, with no holds, open Opportunities, active grants, or service access. Trial history and existing retention deadlines remain.', fields: [reason], submitLabel: 'Deactivate Prospect' })}>Close Prospect access</Button> : null}
    </div><p className="text-sm">{trial.commercialOutcome ? `${trialLabel(trial.commercialOutcome)} · ${trial.commercialOutcomeReason}` : 'Commercial outcome not yet recorded.'}</p>{trial.actualMaterialDisposition ? <p className="text-sm">Residual material: {trial.actualMaterialDisposition}</p> : null}</section> : null}
    <section className="rounded-lg border p-4"><h2 className="mb-3 text-lg font-semibold">Timeline</h2><ol className="space-y-3">{trial.timeline.map((event, index) => <li key={`${event.atUtc}-${index}`} className="text-sm"><p>{event.summary}</p><time className="text-xs text-muted-foreground" dateTime={event.atUtc}>{trialDate(event.atUtc)}</time></li>)}</ol></section>
    {action ? <TrialFormDialog title={action.title} description={action.description} fields={action.fields} submitLabel={action.submitLabel} onClose={() => setAction(null)} onReload={async () => { const refreshed = await queries.detail.refetch(); if (refreshed.error) throw refreshed.error; version.current = refreshed.data!.version }} onSubmit={async (values, key) => { await mutation.mutateAsync({ path: action.path, payload: { ...(action.payload?.(values) ?? values), version: version.current }, key }) }}>{action.content}</TrialFormDialog> : null}
  </main>
}
export function TrialScopeView({ scope }: { scope: TrialScope }) {
  return <div className="space-y-3 text-sm"><p className="whitespace-pre-wrap">{scope.objective}</p><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="text-muted-foreground">Original sample allowance</dt><dd>{scope.sampleAllowance}</dd></div><div><dt className="text-muted-foreground">Submission window</dt><dd>{trialDate(scope.submissionOpensAtUtc)} – {trialDate(scope.submissionClosesAtUtc)}</dd></div><div><dt className="text-muted-foreground">PSeq analyses</dt><dd>{scope.analyses.map(value => `${value.name} (v${value.version})`).join(', ')}</dd></div><div><dt className="text-muted-foreground">Deliverables</dt><dd>{scope.deliverables.map(value => value.name).join(', ')}</dd></div></dl><div><h3 className="font-medium">Submission instructions</h3><p className="whitespace-pre-wrap">{scope.submissionInstructions}</p>{scope.analyses.map(value => <p key={value.id} className="mt-2 whitespace-pre-wrap">{value.name}: {value.instructions}</p>)}</div><div><h3 className="font-medium">Acceptance criteria</h3><p className="whitespace-pre-wrap">{scope.successCriteria}</p></div><p>Residual RNA: retain {scope.residualRetentionDays} days after closure; {scope.materialDisposition === 'Return' ? `return to ${scope.returnDestination}; ${scope.returnHandling}; shipping payer: ${scope.returnShippingPayer}` : 'destroy after the retention period'}.</p><div><h3 className="font-medium">Terms · revision {scope.revision}</h3><p className="whitespace-pre-wrap">{scope.terms}</p><p className="mt-2 font-medium">{scope.ruoStatement}</p></div>{scope.internalValues ? <p className="text-muted-foreground">Internal only · Estimated retail value: {scope.internalValues.estimatedRetailValue} · Anticipated internal cost: {scope.internalValues.anticipatedInternalCost}</p> : null}{scope.decisions.length ? <ul>{scope.decisions.map(value => <li key={value.domain}>{trialLabel(value.domain)}: {trialLabel(value.decision)} · {trialDate(value.atUtc)}{value.reason ? ` · ${value.reason}` : ''}</li>)}</ul> : null}</div>
}
