import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { Download, FileArchive } from 'lucide-react'
import { useState } from 'react'

import { acceptAssemblyQuote, downloadAssemblyOutput, getAssemblyRequest, getOrderErrorMessage, requestAssemblyCancellation, submitAssemblyRequest, type Quote, withdrawAssemblyRequest } from '#/api/order-management'
import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '#/components/ui/dialog'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import { usePhaenoSession } from '#/features/auth/session-context'
import { humanizeStatus, OrderStatusBadge } from './OrderStatusBadge'

export function DataAssemblyDetailPage({ requestId }: { requestId: string }) {
  const { authProvider, session } = usePhaenoSession()
  const queryClient = useQueryClient()
  const [dialog, setDialog] = useState<'accept' | 'cancel' | 'withdraw' | null>(null)
  const [purchaseOrderNumber, setPurchaseOrderNumber] = useState('')
  const [reason, setReason] = useState('')
  const apiEnabled = Boolean(session?.capabilities.canViewDataAssemblyRequests) && authProvider !== 'mock'
  const requestQuery = useQuery({ queryKey: ['data-assembly-request', requestId], queryFn: () => getAssemblyRequest(requestId), enabled: apiEnabled })
  const action = useMutation({
    mutationFn: async (kind: 'submit' | 'accept' | 'cancel' | 'withdraw') => {
      const request = requestQuery.data
      if (!request) throw new Error('The request has not loaded.')
      if (kind === 'submit') return submitAssemblyRequest(request.id, request.version, request.inputFiles)
      if (kind === 'cancel') return requestAssemblyCancellation(request.id, request.version, reason)
      if (kind === 'withdraw') return withdrawAssemblyRequest(request.id, request.version, reason)
      const quote = currentQuote(request.quotes)
      if (!quote) throw new Error('No current quote is available.')
      return acceptAssemblyQuote(request.id, quote.id, request.version, purchaseOrderNumber)
    },
    onSuccess: async () => { setDialog(null); setReason(''); setPurchaseOrderNumber(''); await queryClient.invalidateQueries({ queryKey: ['data-assembly-request', requestId] }) },
  })

  if (!apiEnabled) return <main className="page-wrap px-4 py-8"><Alert><AlertTitle>Connected request detail is unavailable</AlertTitle><AlertDescription>Use a signed-in Partner session to review this assembly request.</AlertDescription></Alert></main>
  if (requestQuery.isLoading) return <main className="page-wrap px-4 py-8"><p role="status">Loading assembly request…</p></main>
  if (requestQuery.error || !requestQuery.data) return <main className="page-wrap px-4 py-8"><Alert variant="destructive"><AlertTitle>Assembly request could not be loaded</AlertTitle><AlertDescription>{getOrderErrorMessage(requestQuery.error, 'Return to Data assembly and try again.')}</AlertDescription></Alert></main>
  const request = requestQuery.data
  const quote = currentQuote(request.quotes)

  return <main className="page-wrap px-4 py-8">
    <section className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-muted-foreground"><Link to="/data-assembly" className="hover:underline">Data assembly</Link> / <span className="font-mono">{request.requestNumber}</span></p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">{request.projectReference}</h1><OrderStatusBadge status={request.status} /></div><p className="mt-2 text-sm text-muted-foreground">{request.requestNumber} · {request.profileName} v{request.assemblyProfileVersion}</p></div><div className="flex flex-wrap gap-2">{request.canEdit ? <Button type="button" variant="outline" asChild><Link to="/data-assembly/$requestId/edit" params={{ requestId: request.id }}>Edit request</Link></Button> : null}{request.canSubmit ? <Button type="button" onClick={() => action.mutate('submit')} disabled={action.isPending}>Submit for intake</Button> : null}{request.canAcceptQuote ? <Button type="button" onClick={() => setDialog('accept')}>Accept quote</Button> : null}{request.canWithdraw ? <Button type="button" variant="outline" onClick={() => setDialog('withdraw')}>Withdraw</Button> : null}{request.canRequestCancellation ? <Button type="button" variant="outline" onClick={() => setDialog('cancel')}>Request cancellation</Button> : null}</div></section>
    {request.tenantSafeReason ? <Alert className="mb-5"><AlertTitle>Action needed</AlertTitle><AlertDescription>{request.tenantSafeReason}</AlertDescription></Alert> : null}
    {action.error ? <Alert variant="destructive" className="mb-5"><AlertTitle>Request was not updated</AlertTitle><AlertDescription>{getOrderErrorMessage(action.error, 'Reload and try again.')}</AlertDescription></Alert> : null}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(18rem,1fr)]"><div className="space-y-5">
      <Card><CardHeader><CardTitle>Input revisions</CardTitle><CardDescription>The submitted profile, metadata, files, validation, and manifest remain traceable.</CardDescription></CardHeader><CardContent><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-medium text-muted-foreground">CURRENT REVISION</dt><dd className="mt-1">{request.inputRevision || 'Draft'}</dd></div><div><dt className="text-xs font-medium text-muted-foreground">REQUESTED OUTPUT</dt><dd className="mt-1">{request.requestedOutput}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-medium text-muted-foreground">PROJECT METADATA</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{metadataText(request.metadataJson)}</dd></div></dl>{request.inputRevisions.length ? <div className="mt-5 divide-y">{request.inputRevisions.map((revision) => <div key={revision.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">Revision {revision.revision}</p><p className="text-xs text-muted-foreground">Submitted {formatDateTime(revision.submittedAt)}</p>{revision.correctionReason ? <p className="mt-1 text-sm">Correction: {revision.correctionReason}</p> : null}</div><Button type="button" variant="outline" size="sm" onClick={() => downloadJson(`${request.requestNumber}-input-r${revision.revision}.json`, JSON.stringify({ manifest: JSON.parse(revision.manifestJson), validation: JSON.parse(revision.validationSummaryJson) }, null, 2))}><Download data-icon="inline-start" />Input receipt</Button></div>)}</div> : null}<ul className="mt-5 divide-y">{request.inputFiles.map((file) => <li key={file.id} className="flex justify-between gap-3 py-3 text-sm"><span>{file.fileName}</span><span className="text-muted-foreground">Scan: {humanizeStatus(file.scanStatus)}</span></li>)}</ul></CardContent></Card>
      <Card><CardHeader><CardTitle>Output releases</CardTitle><CardDescription>Only immutable outputs that passed review, invoice synchronization, and the applicable credit or payment gate can be downloaded.</CardDescription></CardHeader><CardContent>{request.outputReleases.some((release) => release.releaseStatus === 'Released') ? <div className="space-y-5">{request.outputReleases.filter((release) => release.releaseStatus === 'Released').map((release) => <section key={release.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">Release {release.releaseVersion}</p><p className="text-xs text-muted-foreground">Pipeline {release.pipelineVersion} · Generated {formatDateTime(release.generatedAt)}</p></div><div className="flex items-center gap-2"><OrderStatusBadge status={release.releaseStatus} /><Button type="button" size="sm" variant="outline" onClick={() => downloadJson(`${request.requestNumber}-output-r${release.releaseVersion}.json`, release.manifestJson)}><Download data-icon="inline-start" />Manifest</Button></div></div><ul className="mt-3 divide-y">{release.files.map((file) => <li key={file.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><span className="text-sm">{file.fileName}</span><Button type="button" variant="outline" onClick={() => downloadAssemblyOutput(request.id, release.id, file)}><Download data-icon="inline-start" />Download</Button></li>)}</ul></section>)}</div> : <div className="flex flex-col items-center py-8 text-center"><FileArchive aria-hidden="true" className="mb-2 size-7 text-muted-foreground" /><p className="font-medium">No downloadable outputs</p><p className="mt-1 max-w-md text-sm text-muted-foreground">Outputs may still be processing, under review, synchronizing to QuickBooks, or awaiting payment.</p></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent><ol className="space-y-4">{request.timeline.map((item) => <li key={item.id} className="border-l-2 pl-4"><p className="text-sm font-medium">{humanizeStatus(item.toStatus)}</p><p className="text-xs text-muted-foreground">{formatDateTime(item.occurredAt)}</p>{item.reason ? <p className="mt-1 text-sm">{item.reason}</p> : null}</li>)}</ol></CardContent></Card>
    </div><div className="space-y-5"><Card><CardHeader><CardTitle>Quote and PO</CardTitle><CardDescription>Assembly pricing is per job and immutable by revision.</CardDescription></CardHeader><CardContent>{quote ? <QuoteSummary quote={quote} /> : <p className="text-sm text-muted-foreground">Pricing has not been issued.</p>}{request.purchaseOrderNumber ? <p className="mt-4 border-t pt-4 text-sm">PO <span className="font-mono">{request.purchaseOrderNumber}</span></p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Commercial gate</CardTitle></CardHeader><CardContent>{request.documents.length ? request.documents.map((document) => <div key={document.id} className="border-b py-3 first:pt-0 last:border-0"><div className="flex justify-between gap-2"><span className="text-sm font-medium">{document.kind} {document.documentNumber ?? ''}</span><OrderStatusBadge status={document.syncStatus} /></div><p className="mt-1 text-sm text-muted-foreground">Balance {formatMoney(document.balance, document.currency)}</p></div>) : <p className="text-sm text-muted-foreground">No commercial documents yet.</p>}</CardContent></Card></div></div>
    <Dialog open={dialog === 'accept'} onOpenChange={(open) => !open && setDialog(null)}><DialogContent><DialogHeader><DialogTitle>Accept assembly quote?</DialogTitle><DialogDescription>This freezes the validated input/profile/commercial snapshot and places {request.requestNumber} in the processing queue.</DialogDescription></DialogHeader>{quote ? <QuoteSummary quote={quote} /> : null}<div><Label htmlFor="assemblyPo">Purchase order number <span className="text-[var(--ruby-red,#b4233c)]" aria-hidden="true">*</span></Label><Input id="assemblyPo" value={purchaseOrderNumber} onChange={(event) => setPurchaseOrderNumber(event.target.value)} className="mt-2" /></div><DialogFooter><DialogClose asChild><Button type="button" variant="outline">Keep reviewing</Button></DialogClose><Button type="button" disabled={!purchaseOrderNumber.trim() || action.isPending} onClick={() => action.mutate('accept')}>Accept quote and queue work</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={dialog === 'cancel' || dialog === 'withdraw'} onOpenChange={(open) => !open && setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{dialog === 'withdraw' ? 'Withdraw request?' : 'Request cancellation?'}</DialogTitle><DialogDescription>{dialog === 'withdraw' ? 'This closes the request before processing is placed.' : 'Phaeno will preserve completed processing and financial history while deciding the remaining scope.'}</DialogDescription></DialogHeader><div><Label htmlFor="assemblyCancellationReason">Reason <span className="text-[var(--ruby-red,#b4233c)]" aria-hidden="true">*</span></Label><textarea id="assemblyCancellationReason" value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:outline-none" /></div><DialogFooter><DialogClose asChild><Button type="button" variant="outline">Keep request</Button></DialogClose><Button type="button" variant="destructive" disabled={!reason.trim() || action.isPending} onClick={() => action.mutate(dialog === 'withdraw' ? 'withdraw' : 'cancel')}>{dialog === 'withdraw' ? 'Withdraw request' : 'Request cancellation'}</Button></DialogFooter></DialogContent></Dialog>
  </main>
}

function QuoteSummary({ quote }: { quote: Quote }) { return <div><div className="flex justify-between gap-2"><span className="font-medium">Revision {quote.revision}</span><OrderStatusBadge status={quote.status} /></div><p className="mt-1 text-sm text-muted-foreground">Expires {formatDate(quote.expiresAt)}</p><div className="mt-3 flex justify-between border-t pt-3 font-semibold"><span>Total</span><span>{formatMoney(quote.total, quote.currency)}</span></div></div> }
function currentQuote(quotes: Quote[]) { return quotes.find((quote) => quote.status === 'Issued') ?? quotes[0] ?? null }
function metadataText(value: string) { try { const parsed = JSON.parse(value) as { projectMetadata?: string }; return parsed.projectMetadata ?? value } catch { return value } }
function formatMoney(value: number, currency: string) { return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(value) }
function formatDate(value: string) { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(value)) }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function downloadJson(fileName: string, value: string) { const url = URL.createObjectURL(new Blob([value], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url) }
