import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from '@tanstack/react-router'
import { Download, PackageCheck } from 'lucide-react'
import { useState } from 'react'

import { cancelReagentOrder, createReagentDraftFromPrior, decideReagentAdjustment, getOrderErrorMessage, getReagentOrder, requestReagentCancellation, type ReagentAdjustment } from '#/api/order-management'
import { Alert, AlertDescription, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '#/components/ui/dialog'
import { Label } from '#/components/ui/label'
import { usePhaenoSession } from '#/features/auth/session-context'
import { humanizeStatus, OrderStatusBadge } from './OrderStatusBadge'

export function ReagentOrderDetailPage({ orderId }: { orderId: string }) {
  const { authProvider, session } = usePhaenoSession()
  const queryClient = useQueryClient()
  const navigate = useNavigate()
  const [cancellationOpen, setCancellationOpen] = useState(false)
  const [reason, setReason] = useState('')
  const apiEnabled = Boolean(session?.capabilities.canViewReagentOrders) && authProvider !== 'mock'
  const orderQuery = useQuery({ queryKey: ['reagent-order', orderId], queryFn: () => getReagentOrder(orderId), enabled: apiEnabled })
  const action = useMutation({
    mutationFn: async (input: { kind: 'adjustment'; adjustment: ReagentAdjustment; approved: boolean } | { kind: 'cancel' } | { kind: 'copy' }) => {
      const order = orderQuery.data
      if (!order) throw new Error('The order has not loaded.')
      if (input.kind === 'copy') return createReagentDraftFromPrior(order.id)
      if (input.kind === 'cancel') return order.canCancel
        ? cancelReagentOrder(order.id, order.version, reason)
        : requestReagentCancellation(order.id, order.version, reason)
      return decideReagentAdjustment(order.id, input.adjustment.id, order.version, input.approved)
    },
    onSuccess: async (result, input) => {
      setCancellationOpen(false); setReason('')
      if (input.kind === 'copy') { await navigate({ to: '/reagent-orders/$orderId/edit', params: { orderId: result.id } }); return }
      await queryClient.invalidateQueries({ queryKey: ['reagent-order', orderId] })
    },
  })

  if (!apiEnabled) return <main className="page-wrap px-4 py-8"><Alert><AlertTitle>Connected order detail is unavailable</AlertTitle><AlertDescription>Use a signed-in Partner session to review this reagent order.</AlertDescription></Alert></main>
  if (orderQuery.isLoading) return <main className="page-wrap px-4 py-8"><p role="status">Loading reagent order…</p></main>
  if (orderQuery.error || !orderQuery.data) return <main className="page-wrap px-4 py-8"><Alert variant="destructive"><AlertTitle>Reagent order could not be loaded</AlertTitle><AlertDescription>{getOrderErrorMessage(orderQuery.error, 'Return to Reagent orders and try again.')}</AlertDescription></Alert></main>
  const order = orderQuery.data

  return <main className="page-wrap px-4 py-8">
    <section className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-muted-foreground"><Link to="/reagent-orders" className="hover:underline">Reagent orders</Link> / <span className="font-mono">{order.orderNumber}</span></p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">{order.orderNumber}</h1><OrderStatusBadge status={order.status} /></div><p className="mt-2 text-sm text-muted-foreground">PO {order.purchaseOrderNumber ?? '—'} · Updated {formatDate(order.updatedAt)}</p></div><div className="flex flex-wrap gap-2">{order.placementSnapshotJson ? <Button type="button" variant="outline" onClick={() => downloadJson(`${order.orderNumber}-confirmation.json`, order.placementSnapshotJson!)}><Download data-icon="inline-start" />Order confirmation</Button> : null}{session?.capabilities.canCreateReagentOrders ? <Button type="button" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ kind: 'copy' })}>Create draft from prior</Button> : null}{order.canEdit ? <Button type="button" variant="outline" asChild><Link to="/reagent-orders/$orderId/edit" params={{ orderId: order.id }}>{order.canPlace ? 'Review and place' : 'Edit order'}</Link></Button> : null}{order.canCancel || order.canRequestCancellation ? <Button type="button" variant="outline" onClick={() => setCancellationOpen(true)}>{order.canCancel ? 'Cancel order' : 'Request cancellation'}</Button> : null}</div></section>
    {order.tenantSafeReason ? <Alert className="mb-5"><AlertTitle>Order update</AlertTitle><AlertDescription>{order.tenantSafeReason}</AlertDescription></Alert> : null}
    {action.error ? <Alert variant="destructive" className="mb-5"><AlertTitle>Order was not updated</AlertTitle><AlertDescription>{getOrderErrorMessage(action.error, 'Reload and try again.')}</AlertDescription></Alert> : null}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(18rem,1fr)]"><div className="space-y-5">
      <Card><CardHeader><CardTitle>Items and fulfillment</CardTitle><CardDescription>Placed prices remain frozen. Unshipped active quantity is shown as remaining.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-muted-foreground"><tr><th className="py-2 pr-3">Item</th><th className="px-3 py-2">Ordered</th><th className="px-3 py-2">Shipped</th><th className="px-3 py-2">Remaining</th><th className="py-2 pl-3 text-right">Total</th></tr></thead><tbody>{order.lines.map((line) => <tr key={line.id} className="border-b last:border-0"><td className="py-3 pr-3"><span className="font-medium">{line.description}</span><span className="block text-xs text-muted-foreground">{formatMoney(line.unitPrice, line.currency)} / {line.unit}</span></td><td className="px-3 py-3">{line.quantity}</td><td className="px-3 py-3">{line.shippedQuantity}</td><td className="px-3 py-3">{line.remainingQuantity}</td><td className="py-3 pl-3 text-right">{formatMoney(line.lineTotal, line.currency)}</td></tr>)}</tbody></table></div></CardContent></Card>
      {order.adjustments.filter((item) => item.status === 'Proposed').map((adjustment) => <Card key={adjustment.id}><CardHeader><CardTitle>Substitution approval required</CardTitle><CardDescription>{adjustment.reason}</CardDescription></CardHeader><CardContent><AdjustmentComparison adjustment={adjustment} /><div className="mt-4 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => action.mutate({ kind: 'adjustment', adjustment, approved: false })}>Decline substitution</Button><Button type="button" onClick={() => action.mutate({ kind: 'adjustment', adjustment, approved: true })}>Approve substitution</Button></div></CardContent></Card>)}
      <Card><CardHeader><CardTitle>Shipments</CardTitle><CardDescription>Carrier, tracking, lot or batch, and expiration facts are recorded per shipment.</CardDescription></CardHeader><CardContent>{order.shipments.length ? <div className="space-y-4">{order.shipments.map((shipment) => <section key={shipment.id} className="border-b pb-4 last:border-0 last:pb-0"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{shipment.shipmentNumber}</p><p className="text-sm">{shipment.carrier} {shipment.service ?? ''}</p></div><Button type="button" size="sm" variant="outline" onClick={() => downloadJson(`${order.orderNumber}-${shipment.packingSlipNumber}.json`, JSON.stringify(shipment, null, 2))}><Download data-icon="inline-start" />Packing slip</Button></div><p className="mt-1 text-sm text-muted-foreground">Tracking <span className="font-mono">{shipment.trackingNumber}</span> · Shipped {formatDate(shipment.shippedAt)}</p><ul className="mt-2 text-sm">{shipment.lines.map((line) => <li key={line.id}>Quantity {line.quantity} · Lot {line.lotBatchNumber}{line.expiresAt ? ` · Expires ${formatDate(line.expiresAt)}` : ''}</li>)}</ul></section>)}</div> : <div className="flex flex-col items-center py-8 text-center"><PackageCheck aria-hidden="true" className="mb-2 size-7 text-muted-foreground" /><p className="font-medium">No shipments recorded</p><p className="mt-1 text-sm text-muted-foreground">Phaeno will post each partial or complete shipment here.</p></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent><ol className="space-y-4">{order.timeline.map((item) => <li key={item.id} className="border-l-2 pl-4"><p className="text-sm font-medium">{humanizeStatus(item.toStatus)}</p><p className="text-xs text-muted-foreground">{formatDateTime(item.occurredAt)}</p>{item.reason ? <p className="mt-1 text-sm">{item.reason}</p> : null}</li>)}</ol></CardContent></Card>
    </div><div className="space-y-5"><Card><CardHeader><CardTitle>Delivery snapshot</CardTitle></CardHeader><CardContent><AddressSnapshot json={order.shippingAddressSnapshotJson} />{order.requestedDeliveryDate ? <p className="mt-3 text-sm">Requested by {formatDate(order.requestedDeliveryDate)}</p> : null}{order.shippingInstructions ? <p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{order.shippingInstructions}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Commercial documents</CardTitle><CardDescription>Shipment invoices are separate QuickBooks documents related by this portal order.</CardDescription></CardHeader><CardContent className="space-y-3">{order.documents.map((document) => <div key={document.id} className="border-b pb-3 last:border-0"><div className="flex justify-between gap-2"><span className="text-sm font-medium">{document.kind} {document.documentNumber ?? ''}</span><OrderStatusBadge status={document.syncStatus} /></div><p className="mt-1 text-sm text-muted-foreground">{formatMoney(document.total, document.currency)} · Balance {formatMoney(document.balance, document.currency)}</p></div>)}</CardContent></Card></div></div>
    <Dialog open={cancellationOpen} onOpenChange={setCancellationOpen}><DialogContent><DialogHeader><DialogTitle>{order.canCancel ? 'Cancel' : 'Request cancellation for'} {order.orderNumber}</DialogTitle><DialogDescription>{order.canCancel ? 'The unaccepted draft or placed order will close immediately.' : 'Shipped quantities remain final. Phaeno will decide the unfulfilled scope and any QuickBooks adjustment.'}</DialogDescription></DialogHeader><div><Label htmlFor="reagentCancellationReason">Reason <span className="text-[var(--ruby-red,#b4233c)]" aria-hidden="true">*</span></Label><textarea id="reagentCancellationReason" value={reason} onChange={(event) => setReason(event.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm focus-visible:ring-3 focus-visible:ring-ring/50 focus-visible:outline-none" /></div><DialogFooter><DialogClose asChild><Button type="button" variant="outline">Keep order</Button></DialogClose><Button type="button" variant="destructive" disabled={!reason.trim() || action.isPending} onClick={() => action.mutate({ kind: 'cancel' })}>{order.canCancel ? 'Cancel order' : 'Request cancellation'}</Button></DialogFooter></DialogContent></Dialog>
  </main>
}

function AdjustmentComparison({ adjustment }: { adjustment: ReagentAdjustment }) { const before = parse(adjustment.beforeJson); const after = parse(adjustment.afterJson); return <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border p-3"><p className="text-xs font-medium text-muted-foreground">CURRENT</p><p className="mt-1 text-sm">{String(before.description ?? 'Original reagent')}</p><p className="mt-1 text-sm">{String(before.quantity ?? '')} · {String(before.unitPrice ?? '')}</p></div><div className="rounded-lg border p-3"><p className="text-xs font-medium text-muted-foreground">PROPOSED</p><p className="mt-1 text-sm">{String(after.name ?? 'Proposed reagent')}</p><p className="mt-1 text-sm">{String(after.quantity ?? '')} · {String(after.unitPrice ?? '')}</p></div><p className="sm:col-span-2 text-sm">Total effect: {adjustment.totalDifference >= 0 ? '+' : ''}{adjustment.totalDifference.toFixed(2)}</p></div> }
function AddressSnapshot({ json }: { json: string | null }) { const value = parse(json); return value.label ? <address className="not-italic text-sm leading-6"><strong>{String(value.label)}</strong><br />{String(value.recipient ?? '')}<br />{String(value.line1 ?? '')}{value.line2 ? <><br />{String(value.line2)}</> : null}<br />{String(value.city ?? '')}, {String(value.region ?? '')} {String(value.postalCode ?? '')}</address> : <p className="text-sm text-muted-foreground">Address snapshot unavailable.</p> }
function parse(value: string | null): Record<string, unknown> { try { return value ? JSON.parse(value) as Record<string, unknown> : {} } catch { return {} } }
function formatMoney(value: number, currency: string) { return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(value) }
function formatDate(value: string) { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(value)) }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function downloadJson(fileName: string, value: string) { const url = URL.createObjectURL(new Blob([value], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url) }
