import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { act, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import type { ReactNode } from 'react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { kitRequestDetailFixture as detail, kitRequestFixture as request } from '#/test-helpers/transportation-kit-requests'
import { KitRequestsPanel } from './KitRequestsPanel'
import { KitRequestDetailPage } from './KitRequestDetailPage'
import { KitRequestDispatchDialog } from './KitRequestDispatchDialog'

const mocks = vi.hoisted(() => ({ list: vi.fn(), get: vi.fn(), dispatch: vi.fn(), cancel: vi.fn(), navigate: vi.fn(), allowed: true }))
vi.mock('#/api/transportation-kit-requests', () => ({ getPlatformTransportationKitRequests: mocks.list, getPlatformTransportationKitRequest: mocks.get, dispatchTransportationKitRequest: mocks.dispatch, cancelPlatformTransportationKitRequest: mocks.cancel }))
vi.mock('#/features/auth/session-context', () => ({ usePhaenoSession: () => ({ session: { capabilities: { canManageOrderConfiguration: mocks.allowed } } }) }))
vi.mock('../use-order-draft-guard', () => ({ useOrderDraftGuard: () => vi.fn() }))
vi.mock('@tanstack/react-router', () => ({ useNavigate: () => mocks.navigate, useSearch: () => ({}), Link: ({ children, to, params }: { children: ReactNode; to: string; params?: Record<string, string> }) => <a href={Object.entries(params ?? {}).reduce((path, [key, value]) => path.replace(`$${key}`, value), to)}>{children}</a> }))
function mount(node: ReactNode) { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}>{node}</QueryClientProvider>) }
function fill(label: string, value: string) { fireEvent.change(screen.getByLabelText(new RegExp(label)), { target: { value } }) }
beforeEach(() => { vi.clearAllMocks(); mocks.allowed = true; mocks.list.mockResolvedValue([request]); mocks.get.mockResolvedValue(detail); mocks.dispatch.mockResolvedValue(detail); mocks.cancel.mockResolvedValue({ ...request, status: 'Cancelled' }) })

describe('transportation-kit fulfillment', () => {
  it('links an open request to its dedicated detail without embedding a dispatch form', async () => { mount(<KitRequestsPanel apiEnabled />); expect((await screen.findByRole('link', { name: 'Request 20000000' })).getAttribute('href')).toBe(`/lab-operations/kit-requests/${request.id}`); expect(screen.getByText('Example Customer · Research')).toBeTruthy(); expect(screen.queryByLabelText(/Tracking number/)).toBeNull() })
  it('does not request staff data without configuration access', () => { mocks.allowed = false; mount(<KitRequestDetailPage requestId={request.id} />); expect(screen.getByText('A Phaeno configuration administrator is required.')).toBeTruthy(); expect(mocks.get).not.toHaveBeenCalled() })
  it('shows a frozen address and stock shortage while explaining a blocked dispatch', async () => { mocks.get.mockResolvedValue({ ...detail, availableStockKits: [], canDispatch: false, dispatchBlockedReason: 'Prepare fully registered kits first.' }); mount(<KitRequestDetailPage requestId={request.id} />); expect(await screen.findByText('100 Science Avenue')).toBeTruthy(); expect(screen.getByText('More ready kits needed')).toBeTruthy(); expect(screen.getByText('Prepare fully registered kits first.')).toBeTruthy(); expect((screen.getByRole('button', { name: 'Fulfill request' }) as HTMLButtonElement).disabled).toBe(true) })
  it('validates the required physical-kit selection and keeps the dispatch unsent', async () => { mount(<KitRequestDispatchDialog detail={detail} onClose={vi.fn()} onSaved={vi.fn()} />); fill('Carrier', 'Carrier'); fill('Tracking number', 'TRACK-1'); fireEvent.click(screen.getByRole('button', { name: 'Record dispatch' })); expect(await screen.findByText('Select at least one physical kit to dispatch.')).toBeTruthy(); expect(mocks.dispatch).not.toHaveBeenCalled() })
  it('limits physical-kit selections to the remaining requested quantity', () => { mount(<KitRequestDispatchDialog detail={detail} onClose={vi.fn()} onSaved={vi.fn()} />); fireEvent.click(screen.getByLabelText(/KIT-001/)); fireEvent.click(screen.getByLabelText(/KIT-002/)); expect((screen.getByLabelText(/KIT-003/) as HTMLInputElement).disabled).toBe(true); fireEvent.click(screen.getByLabelText(/KIT-001/)); expect((screen.getByLabelText(/KIT-003/) as HTMLInputElement).disabled).toBe(false) })
  it('records a partial dispatch with request version and reuses the same key on a failed retry', async () => { mocks.dispatch.mockRejectedValue(new Error('Temporary dispatch failure.')); mount(<KitRequestDispatchDialog detail={detail} onClose={vi.fn()} onSaved={vi.fn()} />); fireEvent.click(screen.getByLabelText(/KIT-001/)); fill('Carrier', 'Carrier'); fill('Tracking number', 'TRACK-1'); fireEvent.click(screen.getByRole('button', { name: 'Record dispatch' })); expect(await screen.findByText('Dispatch was not recorded')).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Record dispatch' })); await waitFor(() => expect(mocks.dispatch).toHaveBeenCalledTimes(2)); expect(mocks.dispatch.mock.calls[0]).toEqual([request.id, expect.objectContaining({ version: 3, stockKitIds: [detail.availableStockKits[0].id], outboundTrackingNumber: 'TRACK-1', fulfilledAt: expect.stringMatching(/Z$/) }), expect.any(String)]); expect(mocks.dispatch.mock.calls[0][2]).toBe(mocks.dispatch.mock.calls[1][2]); expect((screen.getByLabelText(/Tracking number/) as HTMLInputElement).value).toBe('TRACK-1') })
  it('keeps dirty dispatch entries when discard is declined and prevents closing during save', async () => { const close = vi.fn(); vi.spyOn(window, 'confirm').mockReturnValue(false); mocks.dispatch.mockImplementation(() => new Promise(() => {})); mount(<KitRequestDispatchDialog detail={detail} onClose={close} onSaved={vi.fn()} />); fill('Carrier', 'Carrier'); fireEvent.click(screen.getByRole('button', { name: 'Cancel' })); expect(close).not.toHaveBeenCalled(); fireEvent.click(screen.getByLabelText(/KIT-001/)); fill('Tracking number', 'TRACK-1'); fireEvent.click(screen.getByRole('button', { name: 'Record dispatch' })); await waitFor(() => expect((screen.getByRole('button', { name: 'Cancel' }) as HTMLButtonElement).disabled).toBe(true)); expect((screen.getByLabelText(/Carrier/) as HTMLInputElement).disabled).toBe(true) })
  it('shows in-transit and received kits distinctly without offering another dispatch after completion', async () => { mocks.get.mockResolvedValue({ ...detail, canDispatch: false, request: { ...request, status: 'Dispatched', canCancel: false, kits: [{ stockKitId: 'kit-1', kitNumber: 'KIT-SENT', outboundCarrier: 'Carrier', outboundTrackingNumber: 'TRACK-1', dispatchedAt: request.requestedAt, receivedAt: null }, { stockKitId: 'kit-2', kitNumber: 'KIT-RECEIVED', outboundCarrier: 'Carrier', outboundTrackingNumber: 'TRACK-2', dispatchedAt: request.requestedAt, receivedAt: request.requestedAt }] } }); mount(<KitRequestDetailPage requestId={request.id} />); expect(await screen.findByText('On the way')).toBeTruthy(); expect(screen.getByText('Received by Customer')).toBeTruthy(); expect(screen.queryByRole('button', { name: 'Fulfill request' })).toBeNull(); expect(screen.queryByRole('button', { name: 'Actions' })).toBeNull() })
  it('retains an open fulfillment draft when its request refresh fails', async () => {
    const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
    render(<QueryClientProvider client={client}><KitRequestDetailPage requestId={request.id} /></QueryClientProvider>)
    fireEvent.click(await screen.findByRole('button', { name: 'Fulfill request' })); fill('Tracking number', 'RETAIN-THIS')
    mocks.get.mockRejectedValueOnce(new Error('Connection interrupted.'))
    await act(async () => { await client.invalidateQueries({ queryKey: ['platform-transportation-kit-request', request.id] }) })
    const dialog = screen.getByRole('dialog'); expect(await within(dialog).findByText('Request refresh failed')).toBeTruthy()
    expect((within(dialog).getByLabelText(/Tracking number/) as HTMLInputElement).value).toBe('RETAIN-THIS'); expect((within(dialog).getByRole('button', { name: 'Record dispatch' }) as HTMLButtonElement).disabled).toBe(true)
    fireEvent.click(within(dialog).getByRole('button', { name: 'Retry request check' })); await waitFor(() => expect(within(dialog).queryByText('Request refresh failed')).toBeNull())
    expect((within(dialog).getByLabelText(/Tracking number/) as HTMLInputElement).value).toBe('RETAIN-THIS'); expect(mocks.dispatch).not.toHaveBeenCalled()
  })
})
