import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import type { ReactNode } from 'react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { shippingFixture } from '#/test-helpers/sample-shipping'
import { containerDefinition as definition, standardKit as kit } from '#/test-helpers/shipping-containers'
import { DispatchStandardKitDialog, PrepareStandardKitDialog, RegisterStockKitTubesDialog } from './StandardKitDialogs'
import { StandardKitDetailPage } from './StandardKitDetailPage'
import { StandardKitInventoryPanel } from './StandardKitInventoryPanel'

const mocks = vi.hoisted(() => ({ create: vi.fn(), register: vi.fn(), dispatch: vi.fn(), list: vi.fn(), get: vi.fn(), definitions: vi.fn(), shipments: vi.fn(), navigate: vi.fn(), allowed: true }))
vi.mock('#/api/shipping-containers', () => ({ createShippingStockKit: mocks.create, registerShippingStockKitTubes: mocks.register, dispatchShippingStockKit: mocks.dispatch, getShippingStockKits: mocks.list, getShippingStockKit: mocks.get, getShippingContainerDefinitions: mocks.definitions }))
vi.mock('#/api/sample-shipping', () => ({ getPlatformSampleShipments: mocks.shipments }))
vi.mock('#/features/auth/session-context', () => ({ usePhaenoSession: () => ({ authProvider: 'clerk', session: { capabilities: { canManageOrderConfiguration: mocks.allowed } } }) }))
vi.mock('../use-order-draft-guard', () => ({ useOrderDraftGuard: () => vi.fn() }))
vi.mock('@tanstack/react-router', () => ({ useNavigate: () => mocks.navigate, useSearch: () => ({}), Link: ({ children, to, params }: { children: ReactNode; to: string; params?: { kitId: string } }) => <a href={to.replace('$kitId', params?.kitId ?? '')}>{children}</a> }))
function mount(node: ReactNode) { return render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}>{node}</QueryClientProvider>) }
function fill(label: RegExp | string, value: string) { fireEvent.change(screen.getByLabelText(label), { target: { value } }) }
beforeEach(() => { vi.clearAllMocks(); mocks.allowed = true; mocks.create.mockResolvedValue(kit); mocks.register.mockResolvedValue(kit); mocks.dispatch.mockResolvedValue({ ...kit, status: 'Fulfilled' }); mocks.list.mockResolvedValue([kit]); mocks.get.mockResolvedValue(kit); mocks.definitions.mockResolvedValue([definition]); mocks.shipments.mockResolvedValue([]) })
const callbacks = { onClose: vi.fn(), onSaved: vi.fn() }
describe('standard kit preparation and dispatch', () => {
  it('uses a dedicated record from the stock discovery list', async () => { mount(<StandardKitInventoryPanel apiEnabled />); expect((await screen.findByRole('link', { name: kit.kitNumber })).getAttribute('href')).toBe(`/lab-operations/stock-kits/${kit.id}`); expect(screen.queryByLabelText(/Tube supplier/)).toBeNull() })
  it('requires an active configured size and prefills its actual shipper reference', async () => { mount(<PrepareStandardKitDialog definitions={[definition, { ...definition, id: 'draft', isActive: false, commonName: 'Draft size' }]} {...callbacks} />); expect(screen.queryByRole('option', { name: /Draft size/ })).toBeNull(); fill(/Container size/, definition.id); expect((screen.getByLabelText(/Shipper product number/) as HTMLInputElement).value).toBe(definition.supplierProductNumber); fill(/Tube supplier/, 'Tube maker'); fill(/Tube product number/, 'T-001'); fireEvent.click(screen.getByRole('button', { name: 'Prepare standard kit' })); await waitFor(() => expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ containerDefinitionId: definition.id, tubeSupplierName: 'Tube maker', tubeProductNumber: 'T-001', shipperProductNumber: definition.supplierProductNumber, tubeLotNumber: null }))); expect(mocks.create.mock.calls[0][0]).not.toHaveProperty('shipmentId') })
  it('blocks duplicate barcode scans and capacity excess without registering', async () => { mount(<RegisterStockKitTubesDialog kit={{ ...kit, container: { ...kit.container, capacity: 2 } }} {...callbacks} />); fill(/Permanent tube barcodes/, 'A\na'); fireEvent.click(screen.getByRole('button', { name: 'Register tubes' })); expect(await screen.findByText('A barcode appears more than once. Scan each physical tube once.')).toBeTruthy(); fill(/Permanent tube barcodes/, 'A\nB\nC'); fireEvent.click(screen.getByRole('button', { name: 'Register tubes' })); expect(await screen.findByText('Only 2 more tubes fit in this kit.')).toBeTruthy(); expect(mocks.register).not.toHaveBeenCalled() })
  it('registers scanned permanent identities using the displayed kit version', async () => { mount(<RegisterStockKitTubesDialog kit={kit} {...callbacks} />); fill(/Permanent tube barcodes/, '  BARCODE-1\nBARCODE-2  '); fireEvent.click(screen.getByRole('button', { name: 'Register tubes' })); await waitFor(() => expect(mocks.register).toHaveBeenCalledWith(kit.id, { supplierBarcodes: ['BARCODE-1', 'BARCODE-2'], version: kit.version })) })
  it('keeps Customer location deliveries out of the legacy picker and requires full capacity', async () => { const shipment = { ...shippingFixture, authorizationSource: 'ProspectTrialProject' as const, id: '77777777-7777-4777-8777-777777777771' }; mount(<DispatchStandardKitDialog kit={kit} shipments={[shippingFixture, shipment, { ...shipment, id: '77777777-7777-4777-8777-777777777772' }]} {...callbacks} />); expect(screen.getAllByRole('option')).toHaveLength(2); expect((screen.getByRole('button', { name: 'Record dispatch' }) as HTMLButtonElement).disabled).toBe(true); expect(mocks.dispatch).not.toHaveBeenCalled() })
  it('preserves Trial dispatch with its shipment version and timestamp', async () => { const shipment = { ...shippingFixture, authorizationSource: 'ProspectTrialProject' as const, id: '77777777-7777-4777-8777-777777777771' }; const full = { ...kit, container: { ...kit.container, capacity: 1 }, tubes: [{ id: 'tube', supplierBarcode: 'BARCODE-1' }] }; mount(<DispatchStandardKitDialog kit={full} shipments={[shipment]} initialShipmentId={shipment.id} {...callbacks} />); fill(/Carrier/, 'Synthetic carrier'); fill(/Tracking number/, 'TRACK-001'); fireEvent.click(screen.getByRole('button', { name: 'Record dispatch' })); await waitFor(() => expect(mocks.dispatch).toHaveBeenCalledWith(kit.id, expect.objectContaining({ shipmentId: shipment.id, version: kit.version, outboundCarrier: 'Synthetic carrier', outboundTrackingNumber: 'TRACK-001', fulfilledAt: expect.stringMatching(/Z$/) }))) })
  it('retains Partner shipments even when they share the Lab Service authorization source', () => {
    const partner = { ...shippingFixture, organizationKind: 'Partner', authorizationReference: 'PARTNER-JOB' }
    mount(<DispatchStandardKitDialog kit={kit} shipments={[{ ...shippingFixture, organizationKind: 'Customer', authorizationSourceId: 'customer-job' }, partner]} {...callbacks} />)
    expect(screen.getByRole('option', { name: /PARTNER-JOB/ })).toBeTruthy(); expect(screen.getAllByRole('option')).toHaveLength(2)
  })
  it('keeps unsuccessful registration drafts and blocks accidental dirty close', async () => { mocks.register.mockRejectedValue(new Error('Kit changed.')); const close = vi.fn(); vi.spyOn(window, 'confirm').mockReturnValue(false); mount(<RegisterStockKitTubesDialog kit={kit} onClose={close} onSaved={vi.fn()} />); fill(/Permanent tube barcodes/, 'BARCODE-1'); fireEvent.click(screen.getByRole('button', { name: 'Register tubes' })); expect(await screen.findByText('Kit changes were not saved')).toBeTruthy(); fireEvent.click(screen.getByRole('button', { name: 'Cancel' })); expect(close).not.toHaveBeenCalled(); expect((screen.getByLabelText(/Permanent tube barcodes/) as HTMLTextAreaElement).value).toBe('BARCODE-1') })
  it('shows dispatched kit facts without registration or dispatch actions', async () => { mocks.get.mockResolvedValue({ ...kit, status: 'OnTheWay', authorizationReference: 'JOB-1' }); mount(<StandardKitDetailPage kitId={kit.id} />); await screen.findByRole('heading', { name: kit.kitNumber }); expect(screen.getByText('On the way')).toBeTruthy(); expect(screen.queryByRole('button', { name: 'Register tubes' })).toBeNull(); expect(screen.queryByRole('button', { name: 'Record dispatch' })).toBeNull() })
  it('does not load standard kits for a user without configuration access', () => { mocks.allowed = false; mount(<StandardKitDetailPage kitId={kit.id} />); expect(screen.getByText('A Phaeno configuration administrator is required.')).toBeTruthy(); expect(mocks.get).not.toHaveBeenCalled() })
})
