import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { getLabJobSequencing, getLabOperationsError, type LabJobSequencingBatch, type LabLibrary, type LabSpecimen } from '#/api/lab-operations'
import { Alert, AlertDescription } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { labCount, labStatus } from './lab-presentation'
import { vendorStage } from './vendor-workflow'
import { parseLabSection } from './lab-sections'

const date = (value: string | null) => value ? new Date(value).toLocaleString() : 'Not recorded'
type Member = LabJobSequencingBatch['libraries'][number]
function LibraryOutcome({ member }: { member: Member }) {
  return <div><span className={member.outcome === 'Failure' ? 'font-medium text-destructive' : undefined}>{member.outcome ?? 'Not recorded'}</span>{member.outcomeReason ? <p className="mt-1 whitespace-pre-wrap text-xs text-muted-foreground">{member.outcomeReason}</p> : null}</div>
}

export function JobSequencingPanel({ workOrderId, libraries, specimens, specimenId }: { specimenId?: string; workOrderId: string; libraries: LabLibrary[]; specimens: LabSpecimen[] }) {
  const query = useQuery({ queryKey: specimenId ? ['lab-job-sequencing', workOrderId, specimenId] : ['lab-job-sequencing', workOrderId], queryFn: () => specimenId ? getLabJobSequencing(workOrderId, specimenId) : getLabJobSequencing(workOrderId), refetchInterval: 60_000 })
  const specimenName = (id: string) => specimens.find(specimen => specimen.id === id)?.accessionNumber ?? 'Not accessioned'
  const assignedIds = new Set(query.data?.flatMap(item => item.libraries.map(member => member.libraryId)) ?? [])
  const unassigned = libraries.filter(library => !assignedIds.has(library.id))
  return <div className="space-y-4">
    <Card className="gap-0 py-0"><CardHeader className="border-b bg-muted/50 p-4"><CardTitle>Sequencing</CardTitle><CardDescription>{specimenId ? 'This specimen’s' : 'This Job’s'} libraries and vendor batch progress. Recorded vendor outcomes remain separate from scientific approval and result release.</CardDescription><CardAction><Button asChild variant="outline" size="sm"><Link to="/lab-operations" search={previous => ({ ...previous, section: 'batches' })}>Open sequencing batches</Link></Button></CardAction></CardHeader>
      <CardContent className="p-4">
        {query.isPending ? <p role="status">Loading {specimenId ? 'this specimen’s' : 'this Job’s'} sequencing…</p> : query.isError ? <Alert variant="destructive"><AlertDescription>{getLabOperationsError(query.error, 'Sequencing could not be loaded.')} <Button variant="outline" onClick={() => void query.refetch()}>Retry sequencing</Button></AlertDescription></Alert> : !libraries.length ? <p>No libraries have been recorded for {specimenId ? 'this specimen' : 'this Job'}.</p> : <p>{labCount(query.data.length, 'linked batch', 'linked batches')} · {labCount(assignedIds.size, 'assigned library', 'assigned libraries')} · {labCount(unassigned.length, 'unassigned library', 'unassigned libraries')}</p>}
      </CardContent>
    </Card>
    {query.isSuccess ? query.data.map(({ batch, sequencingStartedAtUtc, sequencingCompletedAtUtc, libraries: members }) => <Card key={batch.id} className="gap-0 overflow-hidden py-0">
      <CardHeader className="border-b bg-muted/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><CardTitle><Link to="/lab-operations/batches/$batchId" params={{ batchId: batch.id }} search={previous => ({ ...previous, section: 'batches' })} className="wrap-anywhere font-medium text-primary underline-offset-4 hover:underline focus-visible:underline">{batch.batchNumber}</Link></CardTitle><CardDescription>{batch.name !== batch.batchNumber ? batch.name + ' · ' : ''}{labCount(members.length, specimenId ? 'specimen library' : 'Job library', specimenId ? 'specimen libraries' : 'Job libraries')} · {labCount(batch.memberCount, 'total batch library', 'total batch libraries')}</CardDescription></div><span className="rounded-full border bg-muted px-2 py-1 text-xs font-medium">{batch.status === 'Draft' ? 'Draft · ' : ''}{vendorStage(batch)}</span></div></CardHeader>
      <CardContent className="space-y-4 p-4"><dl className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4">
        {[[ 'Vendor', batch.providerName ?? 'Not assigned' ], [ 'Vendor ETA', date(batch.expectedCompletionAtUtc) ], [ 'Run started', batch.runNotPerformed ? 'Run not performed' : date(sequencingStartedAtUtc) ], [ 'Run completed', batch.runNotPerformed ? 'Run not performed' : date(sequencingCompletedAtUtc) ], [ 'Results received', date(batch.resultsReceivedAtUtc) ], [ 'Results version', batch.resultsVersion ? 'v' + batch.resultsVersion : 'Not recorded' ]].map(([label, value]) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 wrap-anywhere font-medium">{value}</dd></div>)}
      </dl>
      <div className="hidden lg:block"><table className="w-full text-left text-sm"><caption className="sr-only">This Job’s libraries in {batch.batchNumber}</caption><thead className="border-b text-muted-foreground"><tr>{['Library', 'Specimen', 'Sequencing tube', 'Vendor outcome'].map(label => <th key={label} scope="col" className="p-2 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y">{members.map(member => <tr key={member.memberId}><td className="p-2 font-medium wrap-anywhere">{member.libraryKey}</td><td className="p-2"><Link to="/lab-operations/$workOrderId/specimens/$specimenId" params={{ workOrderId, specimenId: member.specimenId }} search={previous => ({ ...previous, section: parseLabSection(previous.section), specimenTab: 'sequencing' })} className="text-primary underline underline-offset-4">{specimenName(member.specimenId)}</Link></td><td className="p-2 wrap-anywhere">{member.sequencingTubeBarcode ?? 'Not prepared'}</td><td className="p-2"><LibraryOutcome member={member} /></td></tr>)}</tbody></table></div>
      <ul className="divide-y lg:hidden" aria-label={'Job libraries in ' + batch.batchNumber}>{members.map(member => <li key={member.memberId} className="space-y-2 py-3"><p className="font-medium wrap-anywhere">{member.libraryKey}</p><dl className="space-y-2 text-sm"><div><dt className="text-muted-foreground">Specimen</dt><dd><Link to="/lab-operations/$workOrderId/specimens/$specimenId" params={{ workOrderId, specimenId: member.specimenId }} search={previous => ({ ...previous, section: parseLabSection(previous.section), specimenTab: 'sequencing' })} className="text-primary underline underline-offset-4">{specimenName(member.specimenId)}</Link></dd></div><div><dt className="text-muted-foreground">Sequencing tube</dt><dd className="wrap-anywhere">{member.sequencingTubeBarcode ?? 'Not prepared'}</dd></div><div><dt className="text-muted-foreground">Vendor outcome</dt><dd><LibraryOutcome member={member} /></dd></div></dl></li>)}</ul>
      </CardContent>
    </Card>) : null}
    {query.isSuccess && unassigned.length ? <Card className="gap-0 py-0"><CardHeader className="border-b bg-muted/50 p-4"><CardTitle>Libraries awaiting batch assignment</CardTitle><CardDescription>Passing libraries can be assigned from Libraries → Add to batch.</CardDescription><CardAction><Button asChild variant="outline" size="sm"><Link to="/lab-operations/$workOrderId" params={{ workOrderId }} search={previous => ({ ...previous, section: parseLabSection(previous.section), tab: 'libraries' })}>Open libraries</Link></Button></CardAction></CardHeader><CardContent className="p-4"><ul className="divide-y">{unassigned.map(library => <li key={library.id} className="flex flex-wrap justify-between gap-2 py-2"><span className="wrap-anywhere font-medium">{library.libraryKey}</span><span className="text-sm text-muted-foreground">{labStatus(library.status)}</span></li>)}</ul></CardContent></Card> : null}
  </div>
}
