import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from '@tanstack/react-router'
import { ChevronRight, FolderPlus } from 'lucide-react'
import { getLabBatchDetail, getLabOperationsDashboard, getLabOperationsError } from '#/api/lab-operations'
import { Button } from '#/components/ui/button'
import { usePhaenoSession } from '#/features/auth/session-context'
import { SequencingBatchActions } from './SequencingBatchActions'
import { VendorResultHistory } from './VendorResultHistory'
import { VendorResultsVersions } from './VendorResultsVersions'
import { LabBatchBarcodeScanner } from './LabBarcodeScanner'
import { SequencingSendoutProgress } from './SequencingSendoutProgress'
import { SequencingTubePairs } from './SequencingTubePairs'
import { PreparationPanel } from './preparation-ui'
import { labAmount, labCount, labStatus } from './lab-presentation'
import { vendorStage, vendorEtaOverdue, vendorNextStep, shipmentPairIssue, canRecordVendorResults } from './vendor-workflow'

function jsonObject(text: string): Record<string, unknown> {
  try { const value: unknown = JSON.parse(text); return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {} } catch { return {} }
}
const textValue = (value: unknown) => typeof value === 'string' || typeof value === 'number' ? String(value) : ''
export function SequencingBatchPage({ batchId }: { batchId: string }) {
  const navigate = useNavigate()
  const openResults = () => void navigate({ to: '/lab-operations/batches/$batchId/record-results', params: { batchId }, search: p => ({ ...p, section: 'batches' }) })
  const { session, authProvider } = usePhaenoSession()
  const enabled = Boolean(session?.capabilities.canManageLabOperations && authProvider !== 'mock')
  const client = useQueryClient()
  const query = useQuery({ queryKey: ['lab-batch', batchId], queryFn: () => getLabBatchDetail(batchId), enabled })
  const resources = useQuery({ queryKey: ['lab-operations'], queryFn: getLabOperationsDashboard, enabled })
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ['lab-batch', batchId] }), client.invalidateQueries({ queryKey: ['lab-operations'] }), client.invalidateQueries({ queryKey: ['lab-sequencing-tubes', batchId] }), client.invalidateQueries({ queryKey: ['lab-result-versions', batchId] })])
  if (!enabled) return <main className="page-wrap py-8"><p role="alert">A connected Phaeno laboratory session is required.</p></main>
  if (query.isPending) return <main className="page-wrap py-8"><p role="status">Loading sequencing batch…</p></main>
  if (query.isError) return <main className="page-wrap space-y-3 py-8"><p role="alert">{getLabOperationsError(query.error, 'The sequencing batch could not be loaded.')}</p><Button variant="outline" onClick={() => void query.refetch()}>Reload batch</Button></main>
  const { batch, tubes, sendout, custody, resultReferences, libraryExceptions } = query.data
  const closed = batch.status === 'Complete' || batch.sendoutStatus === 'Complete'
  const canManage = Boolean(session?.capabilities.canOperateLabWork)
  const needsResultsStep = canManage && batch.sendoutStatus === 'ReceivedByProvider' && !closed
  const next = canRecordVendorResults(batch) ? 'Record results for the vendor job reference, actual run and receipt times, library outcomes and verified FASTQ files.' : batch.status === 'Draft' ? 'Add passing libraries, then begin shipment preparation.' : !batch.sendoutId && (!tubes.members.length || tubes.members.some(member => shipmentPairIssue(member))) ? 'Complete each physical tube pair and its captured Catalog requirement in Actions → Prepare sequencing tubes.' : vendorNextStep(batch.sendoutStatus)
  const manifest = sendout ? jsonObject(sendout.manifestJson) : {}
  const submitted = Array.isArray(manifest.members) ? manifest.members.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : []
  const supplemental = manifest.supplementalDetails && typeof manifest.supplementalDetails === 'object' ? manifest.supplementalDetails as Record<string, unknown> : {}
  const downloadManifest = () => {
    const cell = (value: unknown) => { const text = textValue(value); return `"${(/^[=+@-]/.test(text) ? `'${text}` : text).replaceAll('"', '""')}"` }
    const rows = [['Batch', 'Vendor', 'Sequencing service', 'Address label', 'Destination', 'Carrier', 'Tracking', 'Library', 'Library tube', 'Sequencing tube', 'Transfer quantity', 'Unit', 'Catalog service', 'Catalog version', 'Minimum µL'], ...submitted.map(item => [batch.batchNumber, sendout?.providerName, sendout?.vendorProductName, sendout?.vendorShipmentAddressLabel, sendout?.destination, sendout?.carrier, sendout?.trackingReference, item.libraryKey, item.libraryContainerBarcode, item.containerBarcode, item.quantity, item.quantityUnit, item.catalogServiceName, item.catalogVersion, item.minimumSequencingVolumeUl])]
    const url = URL.createObjectURL(new Blob([rows.map(row => row.map(cell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }))
    const link = document.createElement('a'); link.href = url; link.download = `${batch.batchNumber}-tube-manifest.csv`; link.click(); URL.revokeObjectURL(url)
  }
  const successfulWithoutReference = sendout?.outcome ? tubes.members.filter(member => (libraryExceptions.find(e => e.memberId === member.id)?.outcome ?? sendout.outcome) === 'Success' && !resultReferences.some(r => !r.memberId || r.memberId === member.id)).length : 0
  return <main className="page-wrap space-y-5 py-8">
    <Link to="/lab-operations" search={{ section: 'batches' }} className="text-sm text-primary underline">← Sequencing batches</Link>
    <div className="space-y-3">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0 flex-1"><h1 className="break-words text-2xl font-semibold">{batch.batchNumber}</h1><p className="mt-1 break-words text-sm text-muted-foreground">{batch.name !== batch.batchNumber ? `${batch.name} · ` : ''}{labCount(batch.memberCount, 'library', 'libraries')} · {labStatus(batch.batchType)}</p></div>
        <div className="flex max-w-full flex-wrap items-center gap-2">{batch.resultsVersion ? <span className="rounded-full border bg-muted px-2.5 py-1 text-xs">Results v{batch.resultsVersion}</span> : null}<span className="min-w-0 break-words rounded-full border bg-muted px-2.5 py-1 text-xs font-medium">{vendorStage(batch)}</span><SequencingBatchActions batch={batch} suppliers={resources.data?.suppliers ?? []} canManage={canManage} refresh={refresh} workspace={query.data} onDownloadManifest={downloadManifest} onRecordResults={() => openResults()} showResultsAction={!needsResultsStep} /></div>
      </div>
      {batch.startedAtUtc || batch.completedAtUtc ? <dl className="flex flex-wrap gap-x-6 gap-y-2 text-sm">{batch.startedAtUtc ? <div><dt className="text-muted-foreground">Batch started</dt><dd><time dateTime={batch.startedAtUtc}>{new Date(batch.startedAtUtc).toLocaleString()}</time></dd></div> : null}{batch.completedAtUtc ? <div><dt className="text-muted-foreground">Batch completed</dt><dd><time dateTime={batch.completedAtUtc}>{new Date(batch.completedAtUtc).toLocaleString()}</time></dd></div> : null}</dl> : null}
      {batch.notes ? <p className="whitespace-pre-wrap text-sm">{batch.notes}</p> : null}
    </div>
    <PreparationPanel title="Vendor workflow"><SequencingSendoutProgress batch={batch} sendout={sendout} /></PreparationPanel>
    {!closed || needsResultsStep ? <PreparationPanel title="Next step"><div className="flex flex-wrap items-center gap-3"><p className="min-w-48 flex-1 text-sm">{next}</p>{needsResultsStep ? <Button id={`sequencing-batch-record-results-${batch.id}`} type="button" className="ml-auto shrink-0" onClick={() => openResults()}><FolderPlus aria-hidden="true" data-icon="inline-start" />Record results</Button> : null}</div></PreparationPanel> : null}
    {canManage && batch.status === 'Draft' ? <details className="group/scan rounded-lg border bg-card p-4"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring [&::-webkit-details-marker]:hidden"><ChevronRight aria-hidden="true" className="size-4 shrink-0 group-open/scan:rotate-90" />Scan libraries</summary><div className="mt-3"><LabBatchBarcodeScanner batches={[batch]} suppliers={resources.data?.suppliers ?? []} onAdded={refresh} /></div></details> : null}
    <PreparationPanel title="Sendout and frozen manifest" description="The submitted tube identities and amounts were frozen when the sendout was created.">
      {sendout ? <div className="space-y-3 text-sm"><dl className="grid gap-3 sm:grid-cols-2">{[['Vendor', sendout.providerName], ['Sequencing service', sendout.vendorProductName], ['Shipment address', sendout.vendorShipmentAddressLabel], ['Vendor reference', sendout.providerReference], ['Destination', sendout.destination], ['Carrier', sendout.carrier], ['Tracking reference', sendout.trackingReference]].map(([label, value]) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="whitespace-pre-line break-words">{value || 'Not recorded'}</dd></div>)}<div><dt className="text-muted-foreground">Expected completion</dt><dd className={vendorEtaOverdue(batch) ? 'font-medium text-destructive' : undefined}>{sendout.expectedCompletionAtUtc ? new Date(sendout.expectedCompletionAtUtc).toLocaleString() : 'Not recorded'}{vendorEtaOverdue(batch) ? ' · Overdue' : ''}</dd></div>{[['Shipped', sendout.shippedAtUtc], ['Vendor received', sendout.providerReceivedAtUtc], ['Run started', sendout.sequencingStartedAtUtc], ['Run completed', sendout.sequencingCompletedAtUtc], ['Results received', sendout.resultsReceivedAtUtc]].map(([label, time]) => <div key={label}><dt className="text-muted-foreground">{label}</dt><dd>{time ? new Date(time).toLocaleString() : 'Not recorded'}</dd></div>)}</dl>
        <details className="rounded-md border p-3"><summary className="cursor-pointer rounded-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Frozen tube manifest · {labCount(submitted.length, 'library', 'libraries')}</summary><ul className="mt-3 space-y-2">{submitted.map((item, index) => <li key={textValue(item.memberId) || index} className="rounded-md border p-3"><p className="break-all font-medium">{textValue(item.libraryContainerBarcode)} → {textValue(item.containerBarcode)}</p><p>{textValue(item.libraryKey)} · {labAmount(textValue(item.quantity))} {textValue(item.quantityUnit)}</p><p className="text-muted-foreground">{textValue(item.catalogServiceName)} · Catalog version {textValue(item.catalogVersion)} · minimum {labAmount(textValue(item.minimumSequencingVolumeUl))} µL</p></li>)}</ul></details>
        {typeof supplemental.notes === 'string' && supplemental.notes ? <p className="whitespace-pre-wrap">{supplemental.notes}</p> : null}
      </div> : <p className="text-sm">No sendout has been created.</p>}
    </PreparationPanel>
    <PreparationPanel title="Library results" description="Outcomes apply to each submitted library; the default and exceptions are separate from scientific approval and Customer release.">{sendout?.outcome ? <div className="space-y-3 text-sm"><p className="font-medium">Batch outcome: {sendout.outcome === 'Failure' ? 'Fail' : 'Success'} · {sendout.outcomeAtUtc ? new Date(sendout.outcomeAtUtc).toLocaleString() : ''}</p><p className="whitespace-pre-wrap break-words">{sendout.outcomeNote}</p><ul className="space-y-2">{tubes.members.map(member => { const exception = libraryExceptions.find(e => e.memberId === member.id); return <li key={member.id} className="rounded-md border p-3"><p className="break-words font-medium">{member.libraryKey} · {(exception?.outcome ?? sendout.outcome) === 'Failure' ? 'Fail' : 'Success'}{exception ? ' · Exception' : ''}</p>{exception ? <p className="mt-1 whitespace-pre-wrap break-words">{exception.reason}</p> : null}</li> })}</ul></div> : <p className="text-sm">{batch.status === 'Complete' ? 'Library results have not been recorded.' : 'Record results for library Success/Fail outcomes and exceptions.'}</p>}</PreparationPanel>
    <PreparationPanel title="External result storage" description="Declared locations are unverified. Data processing and release require their own evidence.">{resultReferences.length ? <ul className="space-y-3">{resultReferences.map(reference => <li key={reference.id} className="space-y-1 rounded-md border p-3 text-sm"><p className="break-words font-medium">{reference.label} · {reference.memberId ? tubes.members.find(m => m.id === reference.memberId)?.libraryKey ?? 'Library' : 'Whole batch'}</p><p className="select-all break-all font-mono text-xs">{reference.storageReference}</p><p className="text-muted-foreground">Unverified reference · recorded {new Date(reference.recordedAtUtc).toLocaleString()} · {reference.recordedBy}</p>{reference.notes ? <p className="whitespace-pre-wrap break-words">{reference.notes}</p> : null}</li>)}</ul> : <p className="text-sm">No storage references recorded.</p>}{successfulWithoutReference > 0 ? <p className="mt-3 text-sm">Data handoff outstanding: {labCount(successfulWithoutReference, 'successful library', 'successful libraries')} without a batch or library storage reference.</p> : null}</PreparationPanel>
    <PreparationPanel title="Libraries and tube pairs" description="Library balances and transfers retain their work-order and physical tube lineage.">{tubes.members.length ? <SequencingTubePairs members={tubes.members} canPrint={false} onPrint={() => {}} /> : <p className="text-sm">No libraries assigned yet.</p>}</PreparationPanel>
    {batch.resultsVersion ? <VendorResultsVersions batchId={batch.id} /> : null}
    <PreparationPanel title="Custody and status history" description="Actual occurrence and recorded entry times are separate facts.">{custody.length ? <ol className="space-y-3">{custody.map(event => { const evidence = jsonObject(event.detailsJson); return <li key={event.id} className="space-y-1 rounded-md border p-3 text-sm"><p className="font-medium">{event.eventCode.startsWith('STATUS_') ? labStatus(event.eventCode.slice(7)) : labStatus(event.eventCode)} · {event.locationOrParty}</p><p>Occurred: {new Date(event.occurredAtUtc).toLocaleString()}</p><p>Recorded: {typeof evidence.recordedAtUtc === 'string' ? new Date(evidence.recordedAtUtc).toLocaleString() : 'Separate entry time was not captured'} · {event.recordedBy}</p>{['evidence', 'providerReference', 'carrierReference', 'notes'].map(key => typeof evidence[key] === 'string' && evidence[key] ? <p key={key} className="whitespace-pre-wrap break-words">{labStatus(key)}: {textValue(evidence[key])}</p> : null)}<VendorResultHistory evidence={evidence} libraries={tubes.members} /></li> })}</ol> : <p className="text-sm">No custody or status events recorded.</p>}</PreparationPanel>
  </main>
}
