import { Link } from '@tanstack/react-router'
import type { LabAttemptSpecimen, LabLibrary, LabWorkOrderDetail } from '#/api/lab-operations'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { EvidenceDetails, evidenceLabel } from './InvestigationEvidence'
import { parseLabSection } from './lab-sections'

export function SpecimenLibraries({ workOrderId, specimen, work }: { workOrderId: string; specimen: LabAttemptSpecimen; work: LabWorkOrderDetail }) {
  const libraries = work.libraries.filter(library => library.labSpecimenId === specimen.id)
  const barcode = (id: string) => work.containers.find(container => container.id === id)?.barcode ?? specimen.tubes.find(tube => tube.id === id)?.barcode ?? 'Container barcode unavailable'
  const preparation = (library: LabLibrary) => {
    const attempts = specimen.attempts.filter(attempt => attempt.executionIds.includes(library.preparationExecutionId) && attempt.sourceContainerId === library.sourceContainerId)
    const execution = work.executions.find(item => item.id === library.preparationExecutionId)
    return <div className="space-y-1"><p>{attempts.length === 1 ? `Attempt ${attempts[0].sequence} · ${evidenceLabel(attempts[0].state)}` : 'Preparation attempt not established'}</p><Link to="/lab-operations/executions/$executionId" params={{ executionId: library.preparationExecutionId }} search={previous => ({ ...previous, returnSpecimenId: specimen.id, returnSpecimenTab: 'libraries', section: parseLabSection(previous.section) ?? 'jobs' })} className="text-primary underline underline-offset-4">Open preparation execution</Link><p className="text-xs text-muted-foreground">{execution ? evidenceLabel(execution.status) : 'Execution status unavailable'}</p></div>
  }
  const identity = (library: LabLibrary) => <div className="space-y-1"><p className="wrap-anywhere font-medium">{library.libraryKey}</p><p className="wrap-anywhere text-xs text-muted-foreground">Library tube: {barcode(library.libraryContainerId)}</p></div>
  const source = (library: LabLibrary) => <div className="space-y-1"><p className="wrap-anywhere">{barcode(library.sourceContainerId)}</p><p className="wrap-anywhere text-xs text-muted-foreground">{library.sourceContainerId}</p></div>
  const qc = (library: LabLibrary) => <div className="space-y-2"><Badge variant="outline">{evidenceLabel(library.status)}</Badge>{library.qcResultsJson ? <details><summary className="cursor-pointer text-sm font-medium">QC evidence</summary><div className="mt-2 text-sm"><EvidenceDetails value={library.qcResultsJson} /></div></details> : <p className="text-xs text-muted-foreground">No QC evidence recorded.</p>}</div>
  return <Card className="min-w-0 gap-0 py-0"><CardHeader className="border-b bg-muted/50 p-4"><CardTitle>Specimen libraries</CardTitle><CardDescription>Each library retains its source tube, preparation execution and recorded QC. Sequencing outcomes and result approval are separate.</CardDescription><div className="flex flex-wrap gap-2"><Button asChild variant="outline" size="sm"><Link to="/lab-operations/$workOrderId" params={{ workOrderId }} search={previous => ({ ...previous, section: parseLabSection(previous.section), tab: 'libraries' })}>Manage Job libraries</Link></Button><Button asChild variant="outline" size="sm"><Link to="/lab-operations/$workOrderId/specimens/$specimenId" params={{ workOrderId, specimenId: specimen.id }} search={previous => ({ ...previous, section: parseLabSection(previous.section), specimenTab: 'sequencing' })}>Open sequencing & analysis</Link></Button></div></CardHeader><CardContent className="p-4">
    {!libraries.length ? <p className="text-sm">No libraries have been recorded for this specimen.</p> : <><div className="hidden lg:block"><table className="w-full table-fixed text-left text-sm"><caption className="sr-only">Libraries for {specimen.name}</caption><thead className="border-b text-muted-foreground"><tr>{['Library / tube', 'Source tube', 'Preparation', 'Status / QC'].map(label => <th key={label} scope="col" className="p-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y">{libraries.map(library => <tr key={library.id}><td className="p-3 align-top">{identity(library)}</td><td className="p-3 align-top">{source(library)}</td><td className="p-3 align-top">{preparation(library)}</td><td className="p-3 align-top">{qc(library)}</td></tr>)}</tbody></table></div><ul className="divide-y lg:hidden" aria-label="Specimen libraries">{libraries.map(library => <li key={library.id} className="space-y-3 py-4">{identity(library)}<dl className="space-y-3 text-sm"><div><dt className="text-muted-foreground">Source tube</dt><dd>{source(library)}</dd></div><div><dt className="text-muted-foreground">Preparation</dt><dd>{preparation(library)}</dd></div><div><dt className="text-muted-foreground">Status / QC</dt><dd>{qc(library)}</dd></div></dl></li>)}</ul></>}
  </CardContent></Card>
}
