import { useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useSearch } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { getLabSpecimens, getLabOperationsError, type LabAccessionedSample } from '#/api/lab-operations'
import { Alert, AlertDescription } from '#/components/ui/alert'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Field } from '#/components/ui/field'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import { NativeSelect } from '#/components/ui/native-select'
import { parseSpecimenSearch, processingStates, type SpecimenSearch } from './specimen-navigation'
import { evidenceLabel } from './InvestigationEvidence'

export function SpecimenDiscovery({ enabled }: { enabled: boolean }) {
  const filters = parseSpecimenSearch(useSearch({ strict: false }))
  const navigate = useNavigate()
  const search = filters.specimenSearch ?? '', page = filters.specimenPage ?? 1
  const [settledSearch, setSettledSearch] = useState(search)
  useEffect(() => { const timer = setTimeout(() => setSettledSearch(search), 300); return () => clearTimeout(timer) }, [search])
  const waiting = search !== settledSearch
  const query = useQuery({ queryKey: ['lab-specimen-discovery', settledSearch, page, filters.specimenScope, filters.specimenState, filters.specimenBlocked], queryFn: () => getLabSpecimens(settledSearch, page, filters.specimenScope, filters.specimenState, filters.specimenBlocked), enabled: enabled && !waiting })
  const change = (next: SpecimenSearch, replace = false) => void navigate({ to: '/lab-operations', search: previous => ({ ...previous, section: 'specimens', ...next }), replace, resetScroll: false })
  const data = enabled && !waiting && !query.isError ? query.data : undefined
  const identifier = (sample: LabAccessionedSample) => <Link className="wrap-anywhere font-medium text-primary underline underline-offset-4" to="/lab-operations/$workOrderId/specimens/$specimenId" params={{ workOrderId: sample.labWorkOrderId, specimenId: sample.id }} search={previous => ({ ...previous, section: 'specimens', ...filters, specimenPage: data?.page ?? page, specimenTab: 'overview' })}>{sample.customerSampleId}</Link>
  const state = (sample: LabAccessionedSample) => <><Badge variant="outline">{sample.processingState ? evidenceLabel(sample.processingState) : 'Processing not started'}</Badge><p className="mt-1 text-xs text-muted-foreground">Intake: {evidenceLabel(sample.intakeDisposition)} · {sample.historical ? 'Historical Job' : 'Active Job'}</p>{sample.blocked ? <p className="mt-1 text-sm text-destructive">Blocked · open specimen to review</p> : null}{sample.nextAction ? <p className="mt-1 text-sm">{sample.nextAction}</p> : null}</>
  return <Card className="min-w-0 gap-0 overflow-hidden py-0"><CardHeader className="space-y-4 border-b bg-muted/50 p-4"><div><CardTitle>Specimens</CardTitle><CardDescription>Find a specimen and follow its material, processing, sequencing, results and delivery. Historical means its Job is completed or cancelled.</CardDescription></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field className="lg:col-span-2"><Label htmlFor="specimen-search">Search specimens</Label><Input id="specimen-search" type="search" maxLength={255} placeholder="Specimen, accession, source or derived tube, Customer or Job" value={search} onChange={event => change({ specimenSearch: event.target.value || undefined, specimenPage: 1 }, true)} /></Field><Field><Label htmlFor="specimen-scope">Job context</Label><NativeSelect id="specimen-scope" value={filters.specimenScope ?? ''} onChange={event => change({ specimenScope: event.target.value as SpecimenSearch['specimenScope'] || undefined, specimenPage: 1 })}><option value="">Active and historical</option><option value="Active">Active Jobs</option><option value="Historical">Historical Jobs</option></NativeSelect></Field><Field><Label htmlFor="specimen-state">Processing state</Label><NativeSelect id="specimen-state" value={filters.specimenState ?? ''} onChange={event => change({ specimenState: event.target.value || undefined, specimenPage: 1 })}><option value="">All processing states</option>{processingStates.map(value => <option key={value} value={value}>{evidenceLabel(value)}</option>)}</NativeSelect></Field></div>
    <div className="flex flex-wrap items-center gap-3"><label className="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(filters.specimenBlocked)} onChange={event => change({ specimenBlocked: event.target.checked || undefined, specimenPage: 1 })} />Blocked specimens only</label>{search || filters.specimenScope || filters.specimenState || filters.specimenBlocked ? <Button variant="outline" size="sm" onClick={() => change({ specimenSearch: undefined, specimenScope: undefined, specimenState: undefined, specimenBlocked: undefined, specimenPage: 1 })}>Clear filters</Button> : null}</div>
  </CardHeader><CardContent className="space-y-4 p-4" aria-busy={waiting || query.isFetching}>
    {!enabled ? <p>A connected laboratory session is required.</p> : waiting || query.isPending ? <p role="status">Loading specimens…</p> : query.isError ? <Alert variant="destructive"><AlertDescription>{getLabOperationsError(query.error, 'Specimens could not be loaded.')} <Button variant="outline" onClick={() => void query.refetch()}>Retry specimens</Button></AlertDescription></Alert> : null}
    {data ? <>{data.items.length ? <><div className="hidden lg:block"><table className="w-full text-left text-sm"><caption className="sr-only">Specimen directory</caption><thead className="border-b text-muted-foreground"><tr>{['Specimen / accession', 'Customer / Job', 'Current state', 'Received tubes'].map(label => <th className="p-3 font-medium" scope="col" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{data.items.map(sample => <tr key={sample.id}><td className="p-3 align-top">{identifier(sample)}<p className="mt-1 text-xs text-muted-foreground">{sample.accessionNumber ?? 'Awaiting accession'}</p></td><td className="p-3 align-top">{sample.organizationName}<p className="mt-1 text-xs text-muted-foreground">{sample.jobReference}</p></td><td className="p-3 align-top">{state(sample)}</td><td className="p-3 align-top">{sample.tubes.length}</td></tr>)}</tbody></table></div><ul className="divide-y lg:hidden" aria-label="Specimens">{data.items.map(sample => <li key={sample.id} className="space-y-2 py-4">{identifier(sample)}<p className="text-xs text-muted-foreground">{sample.accessionNumber ?? 'Awaiting accession'} · {sample.organizationName} · {sample.jobReference}</p>{state(sample)}<p className="text-sm">{sample.tubes.length} received tubes</p></li>)}</ul></> : <p>No specimens match these filters.</p>}<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground" aria-live="polite">{data.totalCount} specimens · Page {data.page} of {Math.max(1, Math.ceil(data.totalCount / data.pageSize))}</p><nav aria-label="Specimen pages" className="flex gap-2"><Button variant="outline" size="sm" disabled={query.isFetching || data.page <= 1} onClick={() => change({ specimenPage: data.page - 1 })}>Previous</Button><Button variant="outline" size="sm" disabled={query.isFetching || data.page * data.pageSize >= data.totalCount} onClick={() => change({ specimenPage: data.page + 1 })}>Next</Button></nav></div></> : null}
  </CardContent></Card>
}
