import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { useState } from 'react'
import { getSampleInvestigation, getResultLineage } from '#/api/lab-investigation'
import { getScientificWorkspace, scientificKey } from '#/api/lab-scientific-evidence'
import { getLabJobSequencing, type LabExecution, type LabAttemptSpecimen, type LabAttemptWorkspace } from '#/api/lab-operations'
import { vendorStage } from './vendor-workflow'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Label } from '#/components/ui/label'
import { NativeSelect } from '#/components/ui/native-select'
import { EvidenceError, EvidenceList, evidenceLabel } from './InvestigationEvidence'
import { ResultTrace } from './SampleInvestigation'
import { parseLabSection } from './lab-sections'
import { specimenTabs } from './specimen-navigation'

const recordRoute = '/lab-operations/$workOrderId/specimens/$specimenId/evidence/$kind/$recordId' as const
export function SpecimenOverview({ workOrderId, specimen, workspace, executions = [] }: { workOrderId: string; specimen: LabAttemptSpecimen; workspace: LabAttemptWorkspace; executions?: LabExecution[] }) {
  const science = useQuery({ queryKey: scientificKey(workOrderId, specimen.id), queryFn: () => getScientificWorkspace(workOrderId, specimen.id) })
  const sequencing = useQuery({ queryKey: ['lab-job-sequencing', workOrderId, specimen.id], queryFn: () => getLabJobSequencing(workOrderId, specimen.id), refetchInterval: 60_000 })
  const investigation = useQuery({ queryKey: ['sample-investigation', workOrderId, specimen.id], queryFn: () => getSampleInvestigation(workOrderId, specimen.id) })
  const [resultId, setResultId] = useState('')
  const lineage = useQuery({ queryKey: ['result-lineage', workOrderId, specimen.id, resultId], queryFn: () => getResultLineage(workOrderId, specimen.id, resultId), enabled: Boolean(resultId) })
  const data = science.data
  const evidence = investigation.data?.evidence
  const results = [...(evidence?.results ?? []), ...(evidence?.legacyResults ?? [])]
  const scientificLink = (kind: string, id: string, label: string) => <Link to={recordRoute} params={{ workOrderId, specimenId: specimen.id, kind, recordId: id }} search={previous => ({ ...previous, section: parseLabSection(previous.section), specimenTab: 'sequencing' })} className="wrap-anywhere text-primary underline underline-offset-4">{label}</Link>
  const linkedLibraryIds = new Set(data?.libraries.filter(library => specimen.attempts.some(attempt => attempt.id === library.labSpecimenAttemptId)).map(library => library.id))
  return <div className="space-y-4">
    <Card className="gap-0 py-0"><CardHeader className="border-b bg-muted/50 p-4"><CardTitle>Current specimen</CardTitle><CardDescription>Preparation progress, approved runs and delivered results describe separate parts of the lifecycle.</CardDescription></CardHeader><CardContent className="space-y-4 p-4"><dl className="grid gap-4 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">Received material</dt><dd className="mt-1 font-medium">{specimen.receivedTubes} of {specimen.expectedTubes} tubes · {specimen.eligibleTubes} available</dd></div><div><dt className="text-muted-foreground">Runs approved</dt><dd className="mt-1 font-medium">{specimen.successfulRunCount ?? 0} of {specimen.sequencingRunCount ?? 1}</dd></div><div><dt className="text-muted-foreground">Recorded work</dt><dd className="mt-1 font-medium">{specimen.attempts.length} preparation attempts · {data ? data.outputs.length + ' outputs · ' + data.analyses.length + ' analyses' : science.isError ? 'Scientific records unavailable' : 'Scientific records loading'}</dd></div></dl>{specimen.blocker || specimen.nextAction ? <p className="text-sm">{specimen.blocker ?? specimen.nextAction}</p> : data?.libraries.some(library => library.status === 'QcPassed') && !data.outputs.length ? <p className="text-sm">Passing libraries are ready for sequencing. Review batch assignment in Sequencing & analysis.</p> : !specimen.attempts.length ? <p className="text-sm">Review intake and select available source material in Processing.</p> : <p className="text-sm">Follow the recorded work below, or open its owning workspace to continue.</p>}<nav aria-label="Specimen lifecycle" className="flex flex-wrap gap-2">{specimenTabs.filter(tab => tab.value !== 'overview').map(tab => <Button asChild key={tab.value} size="sm" variant="outline"><Link to="/lab-operations/$workOrderId/specimens/$specimenId" params={{ workOrderId, specimenId: specimen.id }} search={previous => ({ ...previous, section: parseLabSection(previous.section), specimenTab: tab.value })}>{tab.label}</Link></Button>)}</nav></CardContent></Card>
    <Card className="gap-0 py-0"><CardHeader className="border-b bg-muted/50 p-4"><CardTitle>Specimen trace</CardTitle><CardDescription>Source tube → preparation → library → sequencing output → analysis → result version. Every branch uses saved identities; missing relationships remain unknown.</CardDescription></CardHeader><CardContent className="space-y-4 p-4">
      {science.isPending || investigation.isPending ? <p role="status">Loading specimen trace…</p> : null}
      {science.isError || investigation.isError || sequencing.isError ? <div className="space-y-3"><EvidenceError error={science.error ?? investigation.error ?? sequencing.error} /><Button variant="outline" onClick={() => { void science.refetch(); void investigation.refetch(); void sequencing.refetch() }}>Retry trace</Button></div> : null}
      {investigation.data?.limitedSections.length ? <p role="alert" className="text-sm text-destructive">This trace is partial: {investigation.data.limitedSections.map(evidenceLabel).join(', ')} exceed the evidence limit. Use History and saved reports to investigate.</p> : null}
      {results.length ? <div className="space-y-2"><Label htmlFor="specimen-trace-result">Trace an exact result version</Label><NativeSelect id="specimen-trace-result" value={resultId} onChange={event => setResultId(event.target.value)}><option value="">All recorded branches</option>{results.map(result => <option key={result.id} value={result.id}>Version {String(result.packageVersion ?? result.releaseVersion ?? 'Unknown')} · {result.id}</option>)}</NativeSelect>{resultId ? <ResultTrace key={resultId} workOrderId={workOrderId} specimenId={specimen.id} resultId={resultId} /> : null}</div> : investigation.isSuccess ? <p className="text-sm text-muted-foreground">No result versions recorded.</p> : null}
      {data ? specimen.attempts.map(attempt => <section key={attempt.id} className={'space-y-3 rounded-lg border p-4 ' + (lineage.data?.attemptId === attempt.id ? 'border-primary bg-primary/5' : 'bg-muted/20')} aria-label={'Attempt ' + attempt.sequence}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-medium">Attempt {attempt.sequence} · <Link className="wrap-anywhere text-primary underline underline-offset-4" to="/lab-operations/$workOrderId/containers/$containerId" params={{ workOrderId, containerId: attempt.sourceContainerId }} search={previous => ({ ...previous, section: parseLabSection(previous.section) })}>{attempt.sourceBarcode}</Link></h3><Badge variant="outline">{evidenceLabel(attempt.state)}</Badge></div>{attempt.failureEvidence ? <p className="text-sm">Failure evidence: {attempt.failureEvidence}</p> : null}{attempt.holdReason ? <p className="text-sm">Hold: {attempt.holdReason} · {attempt.nextAction}</p> : null}{attempt.preparationBatchId ? <Link className="text-sm text-primary underline" to="/lab-operations/preparation/$preparationBatchId" params={{ preparationBatchId: attempt.preparationBatchId }} search={{ section: 'work' }}>Open preparation tray</Link> : null}<ul className="space-y-2 text-sm">{attempt.executionIds.map(id => <li key={id} className="wrap-anywhere"><Link className="text-primary underline" to="/lab-operations/executions/$executionId" params={{ executionId: id }} search={previous => ({ ...previous, returnSpecimenId: specimen.id, returnSpecimenTab: 'overview', section: parseLabSection(previous.section) })}>{workspace.stages?.find(stage => stage.id === executions.find(execution => execution.id === id)?.labServiceWorkflowStageId)?.name ?? 'Protocol execution'} · {executions.find(execution => execution.id === id)?.status ? evidenceLabel(executions.find(execution => execution.id === id)!.status) : 'Open record'}</Link></li>)}</ul>
        {data.libraries.filter(library => library.labSpecimenAttemptId === attempt.id).map(library => <div key={library.id} className="space-y-3 border-l-2 pl-3"><p className="wrap-anywhere text-sm font-medium">Library {library.libraryKey} · {evidenceLabel(library.status)}</p>{sequencing.data?.filter(batch => batch.libraries.some(member => member.libraryId === library.id)).map(({ batch, libraries: members }) => <p key={batch.id} className="text-sm"><Link to="/lab-operations/batches/$batchId" params={{ batchId: batch.id }} search={{ section: 'batches' }} className="text-primary underline underline-offset-4">{batch.batchNumber}</Link> · {vendorStage(batch)} · Vendor outcome: {members.find(member => member.libraryId === library.id)?.outcome ?? 'Not recorded'}</p>)}{data.outputs.filter(output => output.labLibraryId === library.id && output.labSpecimenAttemptId === attempt.id && output.sourceContainerId === attempt.sourceContainerId).map(output => <div key={output.id} className={'space-y-2 rounded-md border p-3 text-sm ' + (lineage.data?.inputs.some(input => input.id === output.id) ? 'border-primary bg-primary/5' : '')}><p>{scientificLink('sequencing', output.id, output.providerRunReference)} · {output.sequencingRunNumber ? 'Purchased run ' + output.sequencingRunNumber : 'Run number not recorded'}</p><p className="text-xs text-muted-foreground wrap-anywhere">Output {output.id}{output.correctsOutputId ? ' · Corrects ' + output.correctsOutputId : ''}</p>{data.analyses.filter(analysis => data.inputs.some(input => input.labAnalysisRunId === analysis.id && input.labSequencingOutputId === output.id)).map(analysis => <div key={analysis.id} className={'space-y-2 border-l-2 pl-3 ' + (lineage.data?.analysisRunId === analysis.id ? 'border-primary' : '')}>{scientificLink('analysis', analysis.id, analysis.runReference)}{analysis.previousAnalysisRunId ? <p className="text-xs text-muted-foreground">Reanalysis of {analysis.previousAnalysisRunId}</p> : null}{results.filter(result => result.labAnalysisRunId === analysis.id).map(result => <div key={result.id}><Button size="sm" variant="link" className="h-auto p-0 text-left whitespace-normal" onClick={() => setResultId(result.id)}>Result version {String(result.packageVersion ?? result.releaseVersion ?? 'Unknown')} · {result.id}</Button><p className="text-xs text-muted-foreground">{result.state ? evidenceLabel(String(result.state)) : 'Release record'} · {result.releasedAtUtc || result.releasedAt ? 'Released ' + new Date(String(result.releasedAtUtc ?? result.releasedAt)).toLocaleString() : 'No release time recorded'}</p></div>)}</div>)}</div>)}</div>)}
      </section>) : null}
      {data && !specimen.attempts.length ? <p className="text-sm">No source has been selected. Open Processing to review intake and available material.</p> : null}
      {data ? <EvidenceList title="Libraries without a recorded preparation attempt" rows={data.libraries.filter(library => !linkedLibraryIds.has(library.id)).map(library => ({ ...library }))} /> : null}
      {data ? <EvidenceList title="Outputs without a matching recorded source branch" rows={data.outputs.filter(output => !specimen.attempts.some(attempt => attempt.id === output.labSpecimenAttemptId && attempt.sourceContainerId === output.sourceContainerId && data.libraries.some(library => library.id === output.labLibraryId && library.labSpecimenAttemptId === attempt.id))).map(output => ({ ...output }))} /> : null}
      {data ? <EvidenceList title="Analyses without recorded sequencing inputs" rows={data.analyses.filter(analysis => !data.inputs.some(input => input.labAnalysisRunId === analysis.id && data.outputs.some(output => output.id === input.labSequencingOutputId))).map(analysis => ({ ...analysis }))} /> : null}
      {data && investigation.isSuccess ? <EvidenceList title="Results without a recorded producing analysis" rows={results.filter(result => !result.labAnalysisRunId || !data?.analyses.some(analysis => analysis.id === result.labAnalysisRunId))} /> : null}
      <details className="rounded-lg border"><summary className="cursor-pointer bg-muted/50 p-3 text-sm font-medium">Unused and reserve tubes</summary><ul className="space-y-2 p-3 text-sm">{specimen.tubes.filter(tube => !specimen.attempts.some(attempt => attempt.sourceContainerId === tube.id)).map(tube => <li key={tube.id} className="wrap-anywhere">{tube.barcode} · {tube.use}{tube.unavailableReason ? ' · ' + tube.unavailableReason : ''}</li>)}</ul></details>
      <p className="text-xs text-muted-foreground">{workspace.policyKey ? 'Failed retries do not add a purchased run.' : 'Tube-use instruction must be confirmed before source selection.'} Vendor outcomes, scientific approval, release and completed downloads remain separate evidence.</p>
    </CardContent></Card>
  </div>
}
