/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhaenoUsersRouteImport } from './routes/phaeno-users'
import { Route as DataProvisioningRouteImport } from './routes/data-provisioning'
import { Route as DataLibraryRouteImport } from './routes/data-library'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DataLibraryDatasetIdRouteImport } from './routes/data-library.$datasetId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as DataProvisioningSourcesSourceSampleIdRouteImport } from './routes/data-provisioning.sources.$sourceSampleId'

const PhaenoUsersRoute = PhaenoUsersRouteImport.update({
  id: '/phaeno-users',
  path: '/phaeno-users',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProvisioningRoute = DataProvisioningRouteImport.update({
  id: '/data-provisioning',
  path: '/data-provisioning',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLibraryRoute = DataLibraryRouteImport.update({
  id: '/data-library',
  path: '/data-library',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLibraryDatasetIdRoute = DataLibraryDatasetIdRouteImport.update({
  id: '/$datasetId',
  path: '/$datasetId',
  getParentRoute: () => DataLibraryRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const DataProvisioningSourcesSourceSampleIdRoute =
  DataProvisioningSourcesSourceSampleIdRouteImport.update({
    id: '/sources/$sourceSampleId',
    path: '/sources/$sourceSampleId',
    getParentRoute: () => DataProvisioningRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/customers': typeof CustomersRouteWithChildren
  '/data-library': typeof DataLibraryRouteWithChildren
  '/data-provisioning': typeof DataProvisioningRouteWithChildren
  '/phaeno-users': typeof PhaenoUsersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/data-library/$datasetId': typeof DataLibraryDatasetIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/data-provisioning/sources/$sourceSampleId': typeof DataProvisioningSourcesSourceSampleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/customers': typeof CustomersRouteWithChildren
  '/data-library': typeof DataLibraryRouteWithChildren
  '/data-provisioning': typeof DataProvisioningRouteWithChildren
  '/phaeno-users': typeof PhaenoUsersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/data-library/$datasetId': typeof DataLibraryDatasetIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/data-provisioning/sources/$sourceSampleId': typeof DataProvisioningSourcesSourceSampleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/customers': typeof CustomersRouteWithChildren
  '/data-library': typeof DataLibraryRouteWithChildren
  '/data-provisioning': typeof DataProvisioningRouteWithChildren
  '/phaeno-users': typeof PhaenoUsersRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/data-library/$datasetId': typeof DataLibraryDatasetIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/data-provisioning/sources/$sourceSampleId': typeof DataProvisioningSourcesSourceSampleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/customers'
    | '/data-library'
    | '/data-provisioning'
    | '/phaeno-users'
    | '/customers/$customerId'
    | '/data-library/$datasetId'
    | '/demo/tanstack-query'
    | '/data-provisioning/sources/$sourceSampleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/customers'
    | '/data-library'
    | '/data-provisioning'
    | '/phaeno-users'
    | '/customers/$customerId'
    | '/data-library/$datasetId'
    | '/demo/tanstack-query'
    | '/data-provisioning/sources/$sourceSampleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-invite'
    | '/customers'
    | '/data-library'
    | '/data-provisioning'
    | '/phaeno-users'
    | '/customers/$customerId'
    | '/data-library/$datasetId'
    | '/demo/tanstack-query'
    | '/data-provisioning/sources/$sourceSampleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DataLibraryRoute: typeof DataLibraryRouteWithChildren
  DataProvisioningRoute: typeof DataProvisioningRouteWithChildren
  PhaenoUsersRoute: typeof PhaenoUsersRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phaeno-users': {
      id: '/phaeno-users'
      path: '/phaeno-users'
      fullPath: '/phaeno-users'
      preLoaderRoute: typeof PhaenoUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-provisioning': {
      id: '/data-provisioning'
      path: '/data-provisioning'
      fullPath: '/data-provisioning'
      preLoaderRoute: typeof DataProvisioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-library': {
      id: '/data-library'
      path: '/data-library'
      fullPath: '/data-library'
      preLoaderRoute: typeof DataLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-library/$datasetId': {
      id: '/data-library/$datasetId'
      path: '/$datasetId'
      fullPath: '/data-library/$datasetId'
      preLoaderRoute: typeof DataLibraryDatasetIdRouteImport
      parentRoute: typeof DataLibraryRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/data-provisioning/sources/$sourceSampleId': {
      id: '/data-provisioning/sources/$sourceSampleId'
      path: '/sources/$sourceSampleId'
      fullPath: '/data-provisioning/sources/$sourceSampleId'
      preLoaderRoute: typeof DataProvisioningSourcesSourceSampleIdRouteImport
      parentRoute: typeof DataProvisioningRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface DataLibraryRouteChildren {
  DataLibraryDatasetIdRoute: typeof DataLibraryDatasetIdRoute
}

const DataLibraryRouteChildren: DataLibraryRouteChildren = {
  DataLibraryDatasetIdRoute: DataLibraryDatasetIdRoute,
}

const DataLibraryRouteWithChildren = DataLibraryRoute._addFileChildren(
  DataLibraryRouteChildren,
)

interface DataProvisioningRouteChildren {
  DataProvisioningSourcesSourceSampleIdRoute: typeof DataProvisioningSourcesSourceSampleIdRoute
}

const DataProvisioningRouteChildren: DataProvisioningRouteChildren = {
  DataProvisioningSourcesSourceSampleIdRoute:
    DataProvisioningSourcesSourceSampleIdRoute,
}

const DataProvisioningRouteWithChildren =
  DataProvisioningRoute._addFileChildren(DataProvisioningRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DataLibraryRoute: DataLibraryRouteWithChildren,
  DataProvisioningRoute: DataProvisioningRouteWithChildren,
  PhaenoUsersRoute: PhaenoUsersRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
