import type {
  KitAssemblyCase,
  LabServiceOffering,
  LabServiceTiming,
  StandardLabOrderPreview,
} from '#/api/order-bundles'
import type {
  AssemblyProfile,
  DataAssemblyRequest,
  LabServiceOrder,
  ReagentOrder,
  OrderConfiguration,
} from '#/api/order-management'

// Synthetic records only, shared by component checks and isolated browser fixtures.
export const bundleIds = {
  order: '10000000-0000-4000-8000-000000000001',
  organization: '10000000-0000-4000-8000-000000000002',
  offering: '10000000-0000-4000-8000-000000000003',
  profile: '10000000-0000-4000-8000-000000000004',
  unit: '10000000-0000-4000-8000-000000000005',
  case: '10000000-0000-4000-8000-000000000006',
  request: '10000000-0000-4000-8000-000000000007',
  catalog: '10000000-0000-4000-8000-000000000008',
  analysis: '10000000-0000-4000-8000-000000000009',
  department: '10000000-0000-4000-8000-000000000010',
}
export const bundleOffering: LabServiceOffering = {
  id: bundleIds.offering,
  familyId: bundleIds.offering,
  offeringVersion: 2,
  name: 'Synthetic RNA service',
  description: 'Training specimen processing and data assembly.',
  catalogItemId: bundleIds.catalog,
  catalogCode: 'TRAINING-PSEQ',
  catalogName: 'Training PSeq',
  catalogItemVersion: 4,
  unitPrice: 100,
  currency: 'USD',
  analysisIds: [bundleIds.analysis],
  allowedMaterialTypes: ['RNA'],
  allowedBiologicalSources: ['Yeast'],
  includedOutputContract: 'FASTQ reads and transcript assemblies',
  minimumTurnaroundDays: 7,
  maximumTurnaroundDays: 14,
  effectiveFrom: '2026-09-01T00:00:00Z',
  effectiveTo: null,
  isActive: true,
  isSynthetic: false,
  isAvailable: true,
  version: 5,
}
export const bundleTiming: LabServiceTiming = {
  firstReceivedAtUtc: '2026-09-08T10:00:00Z',
  acceptedAtUtc: '2026-09-09T10:00:00Z',
  originalTargetAtUtc: '2026-09-23T10:00:00Z',
  expectedCompletionAtUtc: '2026-09-23T10:00:00Z',
  completedAtUtc: null,
  scheduleHealth: 'OnTrack',
  version: 6,
  canOverrideTiming: true,
  changes: [],
}
export const bundleLabDraft: LabServiceOrder = {
  id: bundleIds.order,
  organizationId: bundleIds.organization,
  orderNumber: 'TRAINING-LAB-1',
  customerReference: 'Synthetic yeast study',
  description: null,
  hasMixedBiologicalSources: false,
  sharedBiologicalSource: 'Yeast',
  storageRequirements: 'Frozen',
  safetyDeclaration: 'Non-hazardous synthetic training materials',
  submissionInstructions: '',
  status: 'DraftRequest',
  requestRevision: 1,
  submittedAt: null,
  placedAt: null,
  completedAt: null,
  tenantSafeReason: null,
  internalNote: null,
  createdAt: '2026-09-07T10:00:00Z',
  updatedAt: '2026-09-07T10:00:00Z',
  version: 3,
  canEdit: true,
  canSubmit: true,
  canAcceptQuote: false,
  canWithdraw: true,
  canRequestCancellation: false,
  samples: [],
  quotes: [],
  resultReleases: [],
  resultFiles: [],
  documents: [],
  cancellationRequests: [],
  timeline: [],
  requestedSpecimenCount: 2,
  sourceGroups: [
    {
      id: bundleIds.analysis,
      biologicalSource: 'Yeast',
      specimenCount: 2,
      version: 1,
    },
  ],
  sampleRosterFinalizedAt: null,
  canEditSamples: false,
  canFinalizeSamples: false,
  canPlaceStandardOrder: true,
  entryMode: 'ManualQuote',
  timing: null,
}
export const bundlePreview: StandardLabOrderPreview = {
  offering: bundleOffering,
  specimenCount: 2,
  subtotal: 200,
  tax: 20,
  total: 220,
  currency: 'USD',
  canPlaceStandardOrder: true,
  blockers: [],
  orderVersion: 3,
  commercialProfileVersion: 7,
  departmentVersion: 8,
  organizationVersion: 9,
  reviewToken: 'synthetic-reviewed-scope',
}
export const bundleProfile: AssemblyProfile = {
  id: bundleIds.profile,
  qboCatalogItemId: bundleIds.catalog,
  name: 'Training transcript assembly',
  profileVersion: 2,
  description: 'Included training outputs',
  instructions: 'Upload the synthetic reads for this kit only.',
  metadataSchemaJson: '{}',
  allowedFileKindsJson: '["FASTQ"]',
  outputContractJson: '{"files":["FASTA","BAM"]}',
  maximumFileSizeBytes: 1_048_576,
  maximumTotalSizeBytes: 2_097_152,
  isActive: true,
  isSynthetic: false,
  version: 4,
}
export const bundleCase: KitAssemblyCase = {
  id: bundleIds.case,
  caseNumber: 'TRAINING-CASE-1',
  originalKitUnitId: bundleIds.unit,
  currentKitUnitId: bundleIds.unit,
  status: 'AwaitingSubmission',
  submissionDeadlineAt: '2027-01-01T10:00:00Z',
  deadlineBasis: 'LabeledExpiration',
  assemblyRequestId: null,
  assemblyRequestNumber: null,
  assemblyRequestStatus: null,
  profile: bundleProfile,
  version: 4,
  canPrepare: true,
  canExtend: true,
  canReplace: true,
  canCancel: true,
  history: [
    {
      id: bundleIds.unit,
      eventType: 'KitShipped',
      at: '2026-09-07T10:00:00Z',
      reason: 'Synthetic training shipment',
    },
  ],
}
export const bundleKitOrder: ReagentOrder = {
  id: bundleIds.order,
  organizationId: bundleIds.organization,
  orderNumber: 'TRAINING-KIT-1',
  status: 'Fulfilled',
  purchaseOrderNumber: 'TRAINING-PO',
  shippingAddressId: null,
  shippingAddressSnapshotJson: JSON.stringify({ label: 'Synthetic Research Laboratory', recipient: 'Training Receiving', line1: '100 Example Lane', city: 'Example', region: 'CA', postalCode: '90000' }),
  requestedDeliveryDate: null,
  shippingInstructions: null,
  placedAt: '2026-09-07T10:00:00Z',
  acceptedAt: '2026-09-07T10:00:00Z',
  fulfilledAt: '2026-09-07T10:00:00Z',
  tenantSafeReason: null,
  internalNote: null,
  createdAt: '2026-09-07T10:00:00Z',
  updatedAt: '2026-09-07T10:00:00Z',
  version: 3,
  canEdit: false,
  canPlace: false,
  canCancel: false,
  canRequestCancellation: false,
  lines: [{ id: bundleIds.offering, offeringId: bundleIds.offering, qboCatalogItemId: bundleIds.catalog, externalItemId: 'TRAINING-KIT', description: 'Training PSeq Kit with included transcript assembly', quantity: 1, unit: 'kit', unitPrice: 100, currency: 'USD', lineTotal: 100, note: null, shippedQuantity: 1, cancelledQuantity: 0, remainingQuantity: 0, estimatedShipDate: null, version: 1, includedOfferingVersion: 5, includedAssemblyProfileId: bundleIds.profile, includedAssemblyProfileVersion: 2 }],
  shipments: [{ id: bundleIds.unit, shipmentNumber: 'TRAINING-SHIPMENT-1', packingSlipNumber: 'TRAINING-PACK-1', carrier: 'Training carrier', service: 'Tracked delivery', trackingNumber: 'TRAINING-TRACK', shippedAt: '2026-09-07T10:00:00Z', lines: [{ id: bundleIds.unit, orderLineId: bundleIds.offering, quantity: 1, lotBatchNumber: 'TRAINING-LOT', expiresAt: '2026-10-03T10:00:00Z' }], version: 1 }],
  adjustments: [],
  documents: [],
  cancellationRequests: [],
  timeline: [],
  isKitBundle: true,
  operationalSummary: 'Kit fulfilled / assembly pending',
  kitUnits: [
    {
      id: bundleIds.unit,
      label: 'TRAINING-KIT-UNIT-1',
      orderLineId: bundleIds.offering,
      status: 'Shipped',
      shippedAt: '2026-09-07T10:00:00Z',
      expiresAt: '2026-10-03T10:00:00Z',
      lotBatchNumber: 'TRAINING-LOT',
      carrier: 'Training carrier',
      trackingNumber: 'TRAINING-TRACK',
      replacesKitUnitId: null,
      replacedByKitUnitId: null,
      version: 2,
    },
  ],
  assemblyCases: [bundleCase],
}
export const bundleAssembly: DataAssemblyRequest = {
  id: bundleIds.request,
  organizationId: bundleIds.organization,
  requestNumber: 'TRAINING-ASSEMBLY-1',
  projectReference: 'Synthetic kit data',
  assemblyProfileId: bundleIds.profile,
  assemblyProfileVersion: 2,
  profileName: bundleProfile.name,
  profileInstructions: bundleProfile.instructions,
  metadataJson: '{}',
  requestedOutput: `Included outputs for ${bundleProfile.name}`,
  processingNotes: null,
  prohibitedDataConfirmed: true,
  status: 'Draft',
  inputRevision: 0,
  purchaseOrderNumber: null,
  submittedAt: null,
  placedAt: null,
  completedAt: null,
  tenantSafeReason: null,
  internalNote: null,
  createdAt: '2026-09-07T10:00:00Z',
  updatedAt: '2026-09-07T10:00:00Z',
  version: 1,
  canEdit: true,
  canSubmit: true,
  canAcceptQuote: false,
  canWithdraw: true,
  canRequestCancellation: false,
  inputRevisions: [],
  quotes: [],
  processingRuns: [],
  outputReleases: [],
  inputFiles: [],
  documents: [],
  cancellationRequests: [],
  timeline: [],
  kitAssemblyCaseId: bundleIds.case,
  kitOrderId: bundleIds.order,
  kitOrderNumber: bundleKitOrder.orderNumber,
  kitCaseNumber: bundleCase.caseNumber,
  isIncludedAssembly: true,
}

export const bundleConfiguration: OrderConfiguration = {
  system: {
    id: bundleIds.order,
    quoteValidityDays: 30,
    sampleSubmissionInstructions: 'Training submission instructions',
    shippingConfigurationJson: '{}',
    sampleConfigurationJson: '{}',
    resultDestinationConfigurationJson: '{}',
    version: 1,
  },
  catalogItems: [
    {
      id: bundleIds.catalog,
      externalItemId: 'TRAINING-PSEQ',
      name: 'Training PSeq bundle',
      description: 'Synthetic training bundle',
      salesUnit: 'specimen',
      basePrice: 100,
      currency: 'USD',
      isActive: true,
      isPSeqLabService: true,
      lastSyncedAt: '2026-09-07T00:00:00Z',
      version: 4,
    },
  ],
  analyses: [
    {
      id: bundleIds.analysis,
      qboCatalogItemId: bundleIds.catalog,
      name: 'Training transcript analysis',
      description: 'Synthetic example',
      submissionInstructions: 'Training instructions',
      requiredIntakeFieldsJson: '{}',
      resultContractJson: '{"files":["FASTA","BAM"]}',
      isActive: true,
      isSynthetic: false,
      version: 1,
    },
  ],
  reagentOfferings: [
    {
      id: bundleIds.offering,
      partnerOrganizationId: bundleIds.organization,
      qboCatalogItemId: bundleIds.catalog,
      itemName: 'Training PSeq Kit',
      negotiatedUnitPrice: 100,
      currency: 'USD',
      sellingUnit: 'kit',
      orderIncrement: 1,
      minimumQuantity: 1,
      maximumQuantity: 10,
      shippingRestrictionsJson: '{}',
      effectiveFrom: '2026-09-01T00:00:00Z',
      effectiveUntil: null,
      isActive: true,
      version: 5,
      includedAssemblyProfileId: bundleIds.profile,
      includedAssemblyProfileName: bundleProfile.name,
      includedAssemblyProfileVersion: 2,
    },
  ],
  assemblyProfiles: [bundleProfile],
  commercialProfiles: [],
}
