import type { SessionCapabilities } from '#/api/session'

export const noSessionCapabilities: SessionCapabilities = {
  canInviteUsers: false,
  canManageMembers: false,
  canChangeMemberRoles: false,
  canLeaveOrganization: false,
  canManageOrganizations: false,
  canManageAllUsers: false,
  canDisableUsers: false,
  canViewDatasetConfiguration: false,
  canManageDatasetDrafts: false,
  canPublishDatasets: false,
  canProvisionOrganizationData: false,
  canViewOrganizationDatasets: false,
  canViewLabServiceOrders: false,
  canCreateLabServiceRequests: false,
  canSubmitLabServiceRequests: false,
  canAcceptLabServiceQuotes: false,
  canRequestLabServiceCancellation: false,
  canViewSampleProgress: false,
  canDownloadLabResults: false,
  canViewReagentOrders: false,
  canCreateReagentOrders: false,
  canPlaceReagentOrders: false,
  canApproveReagentSubstitutions: false,
  canRequestReagentCancellation: false,
  canViewDataAssemblyRequests: false,
  canCreateDataAssemblyRequests: false,
  canSubmitDataAssemblyRequests: false,
  canAcceptDataAssemblyQuotes: false,
  canRequestDataAssemblyCancellation: false,
  canDownloadDataAssemblyOutputs: false,
  canViewAllOperationalOrders: false,
  canManageOrderConfiguration: false,
  canQuoteLabServiceWork: false,
  canManageLabOperations: false,
  canManageReagentFulfillment: false,
  canManageDataAssembly: false,
  canManageOrderIntegrations: false,
  canViewOrderAudit: false,
}
