import type { TrialConfiguration, TrialDetail, TrialScope } from '#/api/trials'
export const trialScope: TrialScope = {
  revision: 1, internalValues: null, name: 'RNA transcript evaluation', objective: 'Evaluate transcript and isoform research outputs from extracted RNA.', sampleAllowance: 2,
  submissionOpensAtUtc: '2026-09-01T12:00:00Z', submissionClosesAtUtc: '2026-10-01T12:00:00Z', submissionInstructions: 'Use sealed frozen RNA tubes and coded research sample references.', successCriteria: 'Approved PSeq analysis and acceptance rules.',
  analyses: [{ id: 'analysis-1', version: 2, name: 'PSeq transcript analysis', instructions: 'Supply extracted RNA and record the organism.', requiredInputsJson: '["organism","biologicalSource"]', resultContractJson: '{}' }],
  deliverables: [{ id: 'deliverable-1', revision: 1, key: 'FASTQ', name: 'FASTQ sequencing reads' }], termsVersion: 'trial-ruo-no-phi-v1', terms: 'No charge. No protected health information or direct personal identifiers. Retain your sample identity mapping outside the Portal.', ruoStatement: 'For Research Use Only. Not for use in diagnostic procedures.', residualRetentionDays: 30, materialDisposition: 'Destroy', returnDestination: null, returnHandling: null, returnShippingPayer: null,
  decisions: [{ domain: 'Commercial', decision: 'Approve', reason: null, actorUserId: null, asDelegate: null, atUtc: '2026-09-01T10:00:00Z' }, { domain: 'ScientificOperations', decision: 'Approve', reason: null, actorUserId: null, asDelegate: null, atUtc: '2026-09-01T11:00:00Z' }],
}
export const trialDetail: TrialDetail = {
  id: 'trial-1', number: 'TR-RESEARCH-01', companyName: 'Synthetic Research', companyId: 'company-1', opportunityId: 'opportunity-1', organizationId: 'prospect-1', departmentId: 'research', status: 'AwaitingAcceptance', version: 4,
  isStaff: false, canManage: false, canAccept: true, canSubmit: false, submissionBlocker: 'An organization administrator must accept the current Trial terms.', approvalDomains: [], originalSamplesRemaining: 2, isOnHold: false, holdReason: null, scheduleEstimate: null, closureReason: null, closedAtUtc: null, residualRetainUntilUtc: null, actualMaterialDisposition: null,
  commercialOutcome: null, commercialOutcomeReason: null, followUpOwnerUserId: null, followUpAtUtc: null, approvedScopeRevision: 1, acceptedScopeRevision: null, scope: trialScope, scopeHistory: [trialScope], samples: [], replacements: [], releases: [], timeline: [{ kind: 'Approved', summary: 'Trial scope approved by Commercial and Scientific Operations.', atUtc: '2026-09-01T11:00:00Z' }],
}
export const trialConfiguration: TrialConfiguration = { canManageConfiguration: false, canAssignPrimary: false, primaryDomains: [], handoffs: [], analyses: [], workflows: [], deliverables: [], defaultDeliverableIds: [], departments: [{ id: 'research', name: 'Research', version: 1 }], destinations: [{ id: 'destination-1', name: 'Phaeno receiving', version: 1 }], sampleTypes: [{ id: 'rna', name: 'Extracted RNA', version: 1 }], staff: [], authorities: [] }
